#!/usr/bin/env Rscript
# ---------------------------------------------------------------------------
# run_report_standalone.R -- cohort-profiler report, single self-contained file
#
# GENERATED from https://github.com/rryesuafuga/cohort-profiler
# at commit 4121a77 on 2026-08-14 by deploy/make_standalone.R. Do not edit by
# hand; regenerate instead.
#
# The entire analysis -- validation, data build, tables, report template and
# the VITAL-HMB spec -- is embedded below. Nothing is downloaded at run time.
# Output: a Word file (.docx) and a web page (.html) always, plus a PDF when
# LibreOffice is present. Still needed on the machine, because no R script
# can contain them:
#   * R 4.1+ and, on first run, internet to install missing CRAN packages
#   * pandoc (bundled with RStudio; plain-R users are pointed to an installer)
#   * LibreOffice for the PDF (optional and free; without it Word itself can
#     export the .docx to PDF via File > Save As)
#
# How to run
#   In RStudio:  open this file, click Source, pick your CSV when asked.
#   Terminal:    Rscript run_report_standalone.R export.csv [output_dir]
#
# Your data never leaves your machine.
# ---------------------------------------------------------------------------

message("cohort-profiler standalone report (embedded code, commit 4121a77)")
message("-------------------------------------------------------------")

if (getRversion() < "4.1") {
  stop("This needs R 4.1 or newer; you have ", getRversion(),
       ". Please update R from https://cran.r-project.org", call. = FALSE)
}

needed <- c("yaml", "readr", "dplyr", "gtsummary", "flextable",
            "rmarkdown", "knitr", "naniar", "ggplot2")
missing <- needed[!vapply(needed, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing)) {
  message("Installing missing packages: ", paste(missing, collapse = ", "))
  install.packages(missing, repos = "https://cloud.r-project.org")
  still <- missing[!vapply(missing, requireNamespace, logical(1), quietly = TRUE)]
  if (length(still)) {
    stop("Could not install: ", paste(still, collapse = ", "),
         ". Check your internet connection and try again.", call. = FALSE)
  }
}
message("Packages: OK")

if (!rmarkdown::pandoc_available("2.0")) {
  stop(paste(
    "pandoc was not found. The simplest fix is to run this script from",
    "RStudio (which bundles pandoc): https://posit.co/download/rstudio-desktop/",
    "Alternatively install pandoc itself from https://pandoc.org/installing.html"),
    call. = FALSE)
}
message("pandoc: OK (", as.character(rmarkdown::pandoc_version()), ")")


# --- embedded analysis code, spec and template ------------------------------

.embedded <- list()

# ==== R/build_data.R (241 lines) ====
.embedded[["R/build_data.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# Turning a validated export into the tidy analysis frame.", 
"#", "# Everything downstream of this file sees only canonical snake_case names,", 
"# declared factor levels and values already inside their declared range.", 
"# Nothing downstream needs to know that REDCap exists.", "# ---------------------------------------------------------------------------", 
"", "#' Blank out the strings that mean \"no answer\".", "#'", 
"#' Folding these into a factor level would invent a category nobody chose.", 
"clean_values <- function(x, na_strings = character(0)) {", "  x <- trimws(as.character(x))", 
"  x[x %in% na_strings] <- NA_character_", "  x[!nzchar(x)] <- NA_character_", 
"  x", "}", "", "# Numeric conversion that reports what it could not parse, rather than warning", 
"# into the void.", "as_numeric_quiet <- function(x) {", "  suppressWarnings(as.numeric(x))", 
"}", "", "#' Build the tidy analysis frame from a validated export.", 
"#'", "#' @param raw A data.frame from [read_export()].", "#' @param spec A `cohort_spec`.", 
"#' @param validation Optional `cohort_validation`; computed if absent.", 
"#' @return A data.frame with one row per participant. Data-quality findings are", 
"#'   attached as an attribute; read them with [data_quality()].", 
"build_analysis_data <- function(raw, spec, validation = NULL) {", 
"  if (is.null(validation)) validation <- validate_export(raw, spec)", 
"  stop_if_invalid(validation)", "", "  df <- raw[validation$rows, , drop = FALSE]", 
"  rownames(df) <- NULL", "  na_strings <- spec$na_strings", 
"", "  out <- list()", "  out[[\".record_id\"]] <- as.character(df[[validation$structural$record_id]])", 
"", "  # --- outcome -------------------------------------------------------------", 
"", "  labels <- spec$outcome$labels", "  y_raw  <- clean_values(df[[validation$structural$outcome]], na_strings)", 
"  if (!is.null(labels)) {", "    lv <- unname(unlist(labels))", 
"    y  <- unname(unlist(labels)[match(y_raw, names(labels))])", 
"    y  <- factor(y, levels = lv)", "  } else {", "    y <- factor(y_raw)", 
"  }", "  out[[spec$outcome$name]] <- y", "", "  # --- soft-failure accumulators -------------------------------------------", 
"", "  range_hits <- list()", "  level_hits <- list()", "", "  # --- source-backed variables --------------------------------------------", 
"", "  for (v in spec_variables(spec)) {", "    if (v$type == \"derived\") next", 
"    col <- validation$columns[[v$name]]", "    if (is.null(col) || is.na(col)) next          # unmatched optional variable", 
"    x <- clean_values(df[[col]], na_strings)", "", "    if (v$type %in% c(\"numeric\")) {", 
"      num  <- as_numeric_quiet(x)", "      bad  <- !is.na(x) & is.na(num)", 
"      if (any(bad)) {", "        level_hits[[length(level_hits) + 1L]] <- data.frame(", 
"          variable = v$name, label = v$label,", "          value = paste(sprintf('\"%s\"', utils::head(sort(unique(x[bad])), 5)),", 
"                        collapse = \", \"),", "          n = sum(bad), issue = \"not a number\",", 
"          stringsAsFactors = FALSE)", "      }", "      r <- clamp_to_range(num, v)", 
"      if (!is.null(r$hit)) range_hits[[length(range_hits) + 1L]] <- r$hit", 
"      out[[v$name]] <- r$value", "", "    } else if (v$type == \"ordinal\") {", 
"      x <- apply_recode(x, v)", "      scores <- unlist(v$scores)", 
"      undeclared <- setdiff(stats::na.omit(unique(x)), names(scores))", 
"      if (length(undeclared)) {", "        level_hits[[length(level_hits) + 1L]] <- data.frame(", 
"          variable = v$name, label = v$label,", "          value = paste(sprintf('\"%s\"', utils::head(sort(undeclared), 5)), collapse = \", \"),", 
"          n = sum(x %in% undeclared, na.rm = TRUE), issue = \"undeclared level\",", 
"          stringsAsFactors = FALSE)", "      }", "      out[[v$name]] <- unname(scores[x])", 
"", "    } else {  # factor or binary", "      x <- apply_recode(x, v)", 
"      declared <- unlist(v$levels)", "      undeclared <- setdiff(stats::na.omit(unique(x)), declared)", 
"      if (length(undeclared)) {", "        # Reported, never folded into \"Other\": that would hide a coding change.", 
"        level_hits[[length(level_hits) + 1L]] <- data.frame(", 
"          variable = v$name, label = v$label,", "          value = paste(sprintf('\"%s\"', utils::head(sort(undeclared), 5)), collapse = \", \"),", 
"          n = sum(x %in% undeclared, na.rm = TRUE), issue = \"undeclared level\",", 
"          stringsAsFactors = FALSE)", "      }", "      out[[v$name]] <- factor(x, levels = declared)", 
"    }", "  }", "", "  analysis <- as.data.frame(out, check.names = FALSE, stringsAsFactors = FALSE)", 
"", "  # --- derived variables ---------------------------------------------------", 
"", "  registry <- derive_registry()", "  for (v in spec_variables(spec, type = \"derived\")) {", 
"    val <- if (!is.null(v$fn)) {", "      fn <- registry[[v$fn]]", 
"      if (is.null(fn)) {", "        stop(sprintf('Spec names an unknown derivation function \"%s\" for variable \"%s\".',", 
"                     v$fn, v$name), call. = FALSE)", "      }", 
"      fn(df, v$args %||% list(), na_strings = na_strings)", 
"    } else {", "      # `expr` is evaluated against variables built so far, so a derived", 
"      # variable can only depend on things already defined above it.", 
"      tryCatch(", "        eval(parse(text = v$expr), envir = analysis),", 
"        error = function(e) {", "          stop(sprintf('Derived variable \"%s\" could not be computed from `%s`: %s',", 
"                       v$name, v$expr, conditionMessage(e)), call. = FALSE)", 
"        })", "    }", "    val <- as.numeric(val)", "    if (length(val) == 1L) val <- rep(val, nrow(analysis))", 
"    r <- clamp_to_range(val, v)", "    if (!is.null(r$hit)) range_hits[[length(range_hits) + 1L]] <- r$hit", 
"    analysis[[v$name]] <- r$value", "  }", "", "  # --- data quality --------------------------------------------------------", 
"", "  quality <- list(", "    n_rows_file    = validation$n_rows,", 
"    n_analytic     = nrow(analysis),", "    soft           = validation$soft,", 
"    unmatched      = validation$unmatched,", "    unused_columns = validation$unused,", 
"    out_of_range   = bind_rows_safe(range_hits),", "    bad_levels     = bind_rows_safe(level_hits),", 
"    missingness    = missingness_table(analysis, spec),", "    checks         = run_checks(analysis, spec)", 
"  )", "  quality$high_missing <- quality$missingness[", "    quality$missingness$pct_missing > 100 * spec$options$missingness_threshold, ,", 
"    drop = FALSE]", "", "  attr(analysis, \"quality\") <- quality", 
"  attr(analysis, \"spec\")    <- spec", "  class(analysis) <- c(\"cohort_data\", class(analysis))", 
"  analysis", "}", "", "#' Data-quality findings attached to an analysis frame.", 
"data_quality <- function(x) attr(x, \"quality\")", "", "# Clamp to the declared range, reporting how many values were dropped. Values", 
"# outside the range become NA: an implausible number is not data.", 
"clamp_to_range <- function(num, v) {", "  if (is.null(v$range)) return(list(value = num, hit = NULL))", 
"  lo <- v$range[[1]]; hi <- v$range[[2]]", "  bad <- !is.na(num) & (num < lo | num > hi)", 
"  hit <- if (any(bad)) {", "    data.frame(variable = v$name, label = v$label, low = lo, high = hi,", 
"               n = sum(bad), stringsAsFactors = FALSE)", "  }", 
"  num[bad] <- NA_real_", "  list(value = num, hit = hit)", "}", 
"", "# Apply the spec's explicit level collapsing. Anything not named here and not", 
"# in `levels` stays as-is so it can be reported as undeclared.", 
"apply_recode <- function(x, v) {", "  if (is.null(v$recode)) return(x)", 
"  map <- unlist(v$recode)", "  hit <- !is.na(x) & x %in% names(map)", 
"  x[hit] <- unname(map[x[hit]])", "  x", "}", "", "bind_rows_safe <- function(lst) {", 
"  lst <- Filter(Negate(is.null), lst)", "  if (!length(lst)) return(NULL)", 
"  do.call(rbind, lst)", "}", "", "#' Per-variable missingness in the analysis frame.", 
"missingness_table <- function(analysis, spec) {", "  vars <- setdiff(names(analysis), \".record_id\")", 
"  lab <- vapply(vars, function(nm) {", "    v <- spec_variable(spec, nm)", 
"    if (!is.null(v)) v$label else spec$outcome$label %||% nm", 
"  }, character(1))", "  dom <- vapply(vars, function(nm) {", 
"    v <- spec_variable(spec, nm)", "    if (!is.null(v)) v$domain else \"Outcome\"", 
"  }, character(1))", "  n_miss <- vapply(vars, function(nm) sum(is.na(analysis[[nm]])), integer(1))", 
"  out <- data.frame(", "    variable = vars, label = unname(lab), domain = unname(dom),", 
"    n_missing = unname(n_miss),", "    pct_missing = round(100 * unname(n_miss) / nrow(analysis), 1),", 
"    stringsAsFactors = FALSE)", "  out[order(-out$pct_missing, out$variable), , drop = FALSE]", 
"}", "", "#' Evaluate the spec's consistency rules.", "#'", "#' Rows where the expression is NA are not evaluable and are excluded from the", 
"#' denominator rather than silently counted as passes.", "run_checks <- function(analysis, spec) {", 
"  if (!length(spec$checks)) return(NULL)", "  rows <- lapply(spec$checks, function(ck) {", 
"    res <- tryCatch(eval(parse(text = ck$expr), envir = analysis),", 
"                    error = function(e) NULL)", "    if (is.null(res)) {", 
"      return(data.frame(check = ck$name, evaluable = 0L, violations = NA_integer_,", 
"                        pct = NA_real_, note = \"could not be evaluated\",", 
"                        stringsAsFactors = FALSE))", "    }", 
"    res <- as.logical(res)", "    ev  <- sum(!is.na(res))", 
"    vi  <- sum(!is.na(res) & !res)", "    data.frame(check = ck$name, evaluable = ev, violations = vi,", 
"               pct = if (ev > 0) round(100 * vi / ev, 1) else NA_real_,", 
"               note = \"\", stringsAsFactors = FALSE)", "  })", 
"  do.call(rbind, rows)", "}")

# ==== R/derive.R (102 lines) ====
.embedded[["R/derive.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# Derived variables.", "#", "# A derived variable is declared in the spec with either an `expr` (evaluated", 
"# against variables already built) or an `fn` naming one of the functions here.", 
"#", "# The rule for everything in this file: inputs come from the spec, never from a", 
"# pattern guessed at run time. The original report built its asset index by", 
"# regex over column names, so adding one checkbox to the REDCap form silently", 
"# redefined socioeconomic status for the whole cohort.", "# ---------------------------------------------------------------------------", 
"", "#' Score a block of Likert items and return the per-person mean.", 
"#'", "#' Items are located by `pattern`, but the expected count is asserted upstream", 
"#' in [validate_export()] so a changed questionnaire fails loudly.", 
"#'", "#' @param raw The filtered raw export.", "#' @param args Spec `args`: `pattern`, `n_items`, `scores`, `min_answered`.", 
"#' @return Numeric vector, NA where too few items were answered.", 
"item_mean <- function(raw, args, na_strings = character(0), ...) {", 
"  cols <- names(raw)[grepl(args$pattern, names(raw))]", "  if (!length(cols)) return(rep(NA_real_, nrow(raw)))", 
"", "  scores <- unlist(args$scores)", "  min_answered <- args$min_answered %||% 1L", 
"", "  scored <- vapply(cols, function(cn) {", "    v <- clean_values(raw[[cn]], na_strings)", 
"    out <- unname(scores[v])", "    # A response that is not in the score map is not a 0; it is unknown.", 
"    as.numeric(out)", "  }, numeric(nrow(raw)))", "  scored <- matrix(scored, nrow = nrow(raw))", 
"", "  answered <- rowSums(!is.na(scored))", "  means <- rowMeans(scored, na.rm = TRUE)", 
"  means[answered < min_answered] <- NA_real_", "  means", "}", 
"", "#' First principal component of a declared list of household assets.", 
"#'", "#' The component's sign is arbitrary in principle, so it is oriented to", 
"#' correlate positively with the number of assets owned. Without that, a", 
"#' rerun on slightly different data can flip the direction of every", 
"#' socioeconomic finding in the report.", "#'", "#' @param raw The filtered raw export.", 
"#' @param args Spec `args`: `columns` (explicit) and `positive` values.", 
"#' @return Numeric vector of scores, NA for rows with no asset data.", 
"asset_pca <- function(raw, args, na_strings = character(0), ...) {", 
"  positive <- args$positive %||% c(\"Checked\", \"Yes\")", "  positive <- tolower(positive)", 
"", "  present <- character(0)", "  for (cn in args$columns) {", 
"    m <- match_column(cn, names(raw))", "    if (m$status == \"ok\") present <- c(present, m$column)", 
"  }", "  if (length(present) < 3L) return(rep(NA_real_, nrow(raw)))", 
"", "  mat <- vapply(present, function(cn) {", "    v <- clean_values(raw[[cn]], na_strings)", 
"    ifelse(is.na(v), NA_real_, as.numeric(tolower(v) %in% positive))", 
"  }, numeric(nrow(raw)))", "  mat <- matrix(mat, nrow = nrow(raw), dimnames = list(NULL, present))", 
"", "  # Drop assets everyone or no one owns: they carry no information and make", 
"  # the correlation matrix singular.", "  keep <- apply(mat, 2, function(z) {", 
"    s <- stats::sd(z, na.rm = TRUE)", "    !is.na(s) && s > 0", 
"  })", "  mat <- mat[, keep, drop = FALSE]", "  if (ncol(mat) < 3L) return(rep(NA_real_, nrow(raw)))", 
"", "  # Mean-impute so a single unanswered checkbox does not drop a participant.", 
"  complete_enough <- rowMeans(!is.na(mat)) >= 0.5", "  for (j in seq_len(ncol(mat))) {", 
"    mu <- mean(mat[, j], na.rm = TRUE)", "    mat[is.na(mat[, j]), j] <- mu", 
"  }", "", "  pc <- stats::prcomp(mat, center = TRUE, scale. = TRUE)", 
"  score <- as.numeric(pc$x[, 1])", "", "  total <- rowSums(mat)", 
"  if (stats::sd(total) > 0 && !is.na(stats::cor(score, total)) &&", 
"      stats::cor(score, total) < 0) {", "    score <- -score", 
"  }", "", "  score[!complete_enough] <- NA_real_", "  score", 
"}", "", "# Registry of functions a spec may name via `fn:`. Keeping it explicit means a", 
"# typo in the spec is an error, not an arbitrary function call.", 
"derive_registry <- function() {", "  list(item_mean = item_mean, asset_pca = asset_pca)", 
"}")

# ==== R/render.R (303 lines) ====
.embedded[["R/render.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# Rendering.", "#", "# One render, then convert. The report is knitted to DOCX with pandoc, and the", 
"# PDF is produced by converting that DOCX with headless LibreOffice. There is", 
"# no LaTeX in this pipeline and no second rendering path, so the two files", 
"# cannot disagree with each other.", "# ---------------------------------------------------------------------------", 
"", "#' Root of the installed app, whether running from source or from a package.", 
"#'", "#' The standalone runner executes from wherever the user's data lives, with", 
"#' the code in a temp directory — walking up from getwd() cannot find it. It", 
"#' announces the code's location via the `cohortprofiler.home` option (or the", 
"#' COHORT_PROFILER_HOME environment variable), which wins when set.", 
"app_root <- function() {", "  override <- getOption(\"cohortprofiler.home\",", 
"                        Sys.getenv(\"COHORT_PROFILER_HOME\", \"\"))", 
"  if (nzchar(override) &&", "      file.exists(file.path(override, \"inst\", \"report.Rmd\"))) {", 
"    return(override)", "  }", "  p <- system.file(package = \"cohortprofiler\")", 
"  if (nzchar(p) && file.exists(file.path(p, \"report.Rmd\"))) return(p)", 
"  # Running from a source checkout: this file lives in <root>/R.", 
"  here <- getwd()", "  for (i in 1:4) {", "    if (file.exists(file.path(here, \"inst\", \"report.Rmd\"))) return(here)", 
"    here <- dirname(here)", "  }", "  getwd()", "}", "", "#' Path to the report template.", 
"report_template <- function() {", "  root <- app_root()", "  cand <- c(file.path(root, \"inst\", \"report.Rmd\"), file.path(root, \"report.Rmd\"))", 
"  hit <- cand[file.exists(cand)]", "  if (!length(hit)) {", 
"    stop(\"Could not find report.Rmd. Expected it at inst/report.Rmd.\", call. = FALSE)", 
"  }", "  hit[[1]]", "}", "", "#' Directory holding the R sources the report needs.", 
"r_source_dir <- function() {", "  root <- app_root()", "  cand <- c(file.path(root, \"R\"), file.path(root, \"Rsrc\"))", 
"  hit <- cand[dir.exists(cand)]", "  if (length(hit)) hit[[1]] else NULL", 
"}", "", "#' Locate the LibreOffice binary, wherever the platform hides it.", 
"#'", "#' PATH lookup alone is not enough: on Windows LibreOffice installs to", 
"#' Program Files without touching PATH, and on macOS it lives inside the", 
"#' application bundle. A collaborator with LibreOffice installed should not", 
"#' be told it is missing.", "#'", "#' @return Full path to soffice, or \"\" when it cannot be found.", 
"find_soffice <- function() {", "  hit <- Sys.which(\"soffice\")", 
"  if (nzchar(hit)) return(unname(hit))", "  hit <- Sys.which(\"libreoffice\")", 
"  if (nzchar(hit)) return(unname(hit))", "", "  candidates <- c(", 
"    file.path(Sys.getenv(\"ProgramFiles\", \"C:/Program Files\"),", 
"              \"LibreOffice\", \"program\", \"soffice.exe\"),", 
"    file.path(Sys.getenv(\"ProgramFiles(x86)\", \"C:/Program Files (x86)\"),", 
"              \"LibreOffice\", \"program\", \"soffice.exe\"),", 
"    \"/Applications/LibreOffice.app/Contents/MacOS/soffice\",", 
"    \"/usr/local/bin/soffice\",", "    \"/opt/homebrew/bin/soffice\",", 
"    \"/snap/bin/libreoffice\"", "  )", "  hit <- candidates[file.exists(candidates)]", 
"  if (length(hit)) hit[[1]] else \"\"", "}", "", "#' Is a PDF conversion possible on this machine?", 
"#'", "#' When it is not — shinyapps.io has no LibreOffice and no way to install", 
"#' one — the report degrades to DOCX only. It must never fall back to a", 
"#' LaTeX render: the PDF is defined as a conversion of the DOCX, and a", 
"#' second rendering path would let the two disagree.", "soffice_available <- function() nzchar(find_soffice())", 
"", "#' Post-process a pandoc DOCX so Word treats it as a finished document.", 
"#'", "#' Two flags live in word/settings.xml, and pandoc sets neither:", 
"#' `updateFields` makes Word refresh the table of contents on open (otherwise", 
"#' every entry shows the stale page number \"1\"), and a `compatibilityMode` of", 
"#' 15 marks the file as current-generation, so Word does not open it in", 
"#' Compatibility Mode. The patched file is re-zipped in place; LibreOffice", 
"#' consuming it afterwards for the PDF doubles as a validity check.", 
"polish_docx <- function(docx) {", "  tmp <- file.path(tempdir(), paste0(\"docx-polish-\", basename(docx)))", 
"  unlink(tmp, recursive = TRUE)", "  dir.create(tmp, recursive = TRUE)", 
"  utils::unzip(docx, exdir = tmp)", "", "  settings <- file.path(tmp, \"word\", \"settings.xml\")", 
"  if (!file.exists(settings)) return(invisible(docx))", "  x <- paste(readLines(settings, warn = FALSE, encoding = \"UTF-8\"),", 
"             collapse = \"\\n\")", "", "  if (!grepl(\"<w:updateFields\", x, fixed = TRUE)) {", 
"    x <- sub(\"(<w:settings[^>]*>)\",", "             '\\\\1<w:updateFields w:val=\"true\"/>', x)", 
"  }", "  compat <- paste0(", "    '<w:compat><w:compatSetting w:name=\"compatibilityMode\" ',", 
"    'w:uri=\"http://schemas.microsoft.com/office/word\" w:val=\"15\"/></w:compat>')", 
"  if (grepl('w:name=\"compatibilityMode\"', x, fixed = TRUE)) {", 
"    x <- gsub('(w:name=\"compatibilityMode\"[^>]*w:val=\")[0-9]+', \"\\\\115\", x)", 
"  } else if (grepl(\"<m:mathPr\", x, fixed = TRUE)) {", "    x <- sub(\"<m:mathPr\", paste0(compat, \"<m:mathPr\"), x)", 
"  } else {", "    x <- sub(\"</w:settings>\", paste0(compat, \"</w:settings>\"), x)", 
"  }", "  writeLines(x, settings, useBytes = TRUE)", "", "  # mirror mode preserves the relative paths under root; cherry-pick would", 
"  # flatten word/document.xml to document.xml and corrupt the package.", 
"  rezipped <- paste0(docx, \".tmp\")", "  unlink(rezipped)", 
"  zip::zip(zipfile = rezipped,", "           files = list.files(tmp, all.files = TRUE, no.. = TRUE),", 
"           root = tmp, mode = \"mirror\")", "  file.copy(rezipped, docx, overwrite = TRUE)", 
"  unlink(rezipped)", "  invisible(docx)", "}", "", "#' Convert a DOCX to PDF with headless LibreOffice.", 
"#'", "#' LibreOffice needs a writable profile directory. In a container the default", 
"#' location under $HOME may not be writable, and the failure surfaces as an", 
"#' empty error, so the profile is pointed at a temporary directory explicitly.", 
"#'", "#' @return Path to the PDF.", "docx_to_pdf <- function(docx, out_dir = dirname(docx), timeout = 180) {", 
"  soffice <- find_soffice()", "  if (!nzchar(soffice)) {", "    stop(paste(\"LibreOffice was not found, so the PDF cannot be produced.\",", 
"               \"Install it free from libreoffice.org (the Word file is\",", 
"               \"unaffected).\"),", "         call. = FALSE)", 
"  }", "  profile <- file.path(tempdir(), \"lo_profile\")", "  dir.create(profile, showWarnings = FALSE, recursive = TRUE)", 
"", "  args <- c(sprintf(\"-env:UserInstallation=file://%s\", profile),", 
"            \"--headless\", \"--norestore\", \"--convert-to\", \"pdf\",", 
"            \"--outdir\", out_dir, docx)", "", "  # R puts its own library directory, and the JVM's, on LD_LIBRARY_PATH. A", 
"  # child process inherits that and LibreOffice then loads the wrong shared", 
"  # libraries and refuses to open any document, reporting only \"source file", 
"  # could not be loaded\". Clearing the variable for this call fixes it, and", 
"  # matters in the container too, where the rocker images set it.", 
"  res <- suppressWarnings(", "    system2(soffice, args, stdout = TRUE, stderr = TRUE,", 
"            env = \"LD_LIBRARY_PATH=\", timeout = timeout))", 
"", "  pdf <- file.path(out_dir, sub(\"\\\\.docx$\", \".pdf\", basename(docx)))", 
"  if (!file.exists(pdf)) {", "    stop(sprintf(\"Converting the report to PDF failed.\\n%s\",", 
"                 paste(res, collapse = \"\\n\")), call. = FALSE)", 
"  }", "  pdf", "}", "", "#' Render the report for one export.", 
"#'", "#' The DOCX is the canonical output and is always rendered. The PDF is only", 
"#' ever a LibreOffice conversion of that DOCX. The HTML version is a second", 
"#' render of the same template — flextable emits real HTML tables — and a", 
"#' fixed seed inside the report keeps its simulated p-values identical to", 
"#' the DOCX's, so the formats cannot disagree.", "#'", "#' @param data_file Path to the REDCap CSV export.", 
"#' @param spec_file Path to the study spec YAML.", "#' @param out_dir Where to write the outputs. Defaults to a fresh temp dir,", 
"#'   because the app directory is not reliably writable in a container.", 
"#' @param basename_out Base name for the output files, without extension.", 
"#' @param formats Any of \"docx\", \"pdf\", \"html\".", "#' @param progress Optional function taking (fraction, message) for UI updates.", 
"#' @return A named list of file paths.", "render_report <- function(data_file,", 
"                          spec_file,", "                          out_dir = NULL,", 
"                          basename_out = \"cohort-report\",", 
"                          formats = c(\"docx\", \"pdf\", \"html\"),", 
"                          progress = NULL) {", "  formats <- match.arg(formats, c(\"docx\", \"pdf\", \"html\"), several.ok = TRUE)", 
"", "  # Resolve every input path before rendering: rmarkdown::render() changes the", 
"  # working directory, after which a relative path no longer means what it did.", 
"  data_file <- normalizePath(data_file, mustWork = TRUE)", "  spec_file <- normalizePath(spec_file, mustWork = TRUE)", 
"  r_dir     <- r_source_dir()", "  if (!is.null(r_dir)) r_dir <- normalizePath(r_dir, mustWork = TRUE)", 
"", "  if (is.null(out_dir)) out_dir <- file.path(tempdir(), paste0(\"render-\", as.integer(Sys.time())))", 
"  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)", 
"", "  say <- function(frac, msg) if (is.function(progress)) progress(frac, msg)", 
"", "  # Knit a copy in the output directory: rendering in place would write", 
"  # intermediates into the app directory.", "  template <- report_template()", 
"  rmd <- file.path(out_dir, paste0(basename_out, \".Rmd\"))", 
"  file.copy(template, rmd, overwrite = TRUE)", "", "  say(0.1, \"Checking the export against the spec\")", 
"", "  # The document title comes from the spec, so it is read here rather than", 
"  # hardcoded: the Rmd's YAML header is evaluated before its setup chunk runs.", 
"  spec <- read_spec(spec_file)", "  title <- paste(c(spec$study, spec$title), collapse = \" \")", 
"  if (!nzchar(trimws(title))) title <- \"Cohort Profile\"", 
"", "  docx <- file.path(out_dir, paste0(basename_out, \".docx\"))", 
"  say(0.2, \"Building tables\")", "", "  rmarkdown::render(", 
"    input = rmd,", "    output_format = rmarkdown::word_document(toc = TRUE, toc_depth = 2),", 
"    output_file = basename(docx),", "    output_dir = out_dir,", 
"    intermediates_dir = out_dir,", "    knit_root_dir = out_dir,", 
"    params = list(", "      data_file      = data_file,", "      spec_file      = spec_file,", 
"      r_dir          = r_dir,", "      title_override = title", 
"    ),", "    envir = new.env(parent = globalenv()),", "    quiet = TRUE", 
"  )", "  if (!file.exists(docx)) {", "    stop(\"The report did not produce a Word file.\", call. = FALSE)", 
"  }", "  polish_docx(docx)", "", "  out <- list(docx = docx)", 
"", "  if (\"html\" %in% formats) {", "    say(0.65, \"Rendering the web version\")", 
"    html <- file.path(out_dir, paste0(basename_out, \".html\"))", 
"    rmarkdown::render(", "      input = rmd,", "      # Styled to read like the original study report: a floating sidebar", 
"      # contents panel, numbered sections and a Bootstrap theme. All of it", 
"      # stays inside the single self-contained file.", "      output_format = rmarkdown::html_document(", 
"        toc = TRUE, toc_depth = 2, toc_float = TRUE,", "        number_sections = TRUE, theme = \"cosmo\"", 
"      ),", "      output_file = basename(html),", "      output_dir = out_dir,", 
"      intermediates_dir = out_dir,", "      knit_root_dir = out_dir,", 
"      params = list(", "        data_file      = data_file,", 
"        spec_file      = spec_file,", "        r_dir          = r_dir,", 
"        title_override = title", "      ),", "      envir = new.env(parent = globalenv()),", 
"      quiet = TRUE", "    )", "    if (!file.exists(html)) {", 
"      stop(\"The report did not produce an HTML file.\", call. = FALSE)", 
"    }", "    out$html <- html", "  }", "", "  # The knitted copy of the template is plumbing, not a deliverable; leaving", 
"  # it next to the outputs only confuses whoever opens the folder.", 
"  unlink(rmd)", "", "  if (\"pdf\" %in% formats) {", "    say(0.85, \"Converting to PDF\")", 
"    out$pdf <- docx_to_pdf(docx, out_dir)", "  }", "  if (!\"docx\" %in% formats) out$docx <- NULL", 
"", "  say(1, \"Done\")", "  out", "}", "", "#' Bundle rendered outputs into a zip.", 
"zip_outputs <- function(paths, zipfile) {", "  paths <- unlist(paths, use.names = FALSE)", 
"  paths <- paths[!is.na(paths) & file.exists(paths)]", "  if (!length(paths)) stop(\"Nothing to zip.\", call. = FALSE)", 
"  zip::zip(zipfile, files = basename(paths), root = dirname(paths[[1]]))", 
"  zipfile", "}")

# ==== R/spec.R (155 lines) ====
.embedded[["R/spec.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# Reading and interrogating a study spec.", "#", "# Nothing in this file knows anything about VITAL-HMB. Everything study-specific", 
"# lives in spec/*.yaml.", "# ---------------------------------------------------------------------------", 
"", "#' Read a study spec from YAML.", "#'", "#' Applies defaults and checks the spec is internally coherent. Problems with", 
"#' the spec itself are the study team's problem, not the data's, so they abort", 
"#' immediately with a message naming the offending variable.", 
"#'", "#' @param path Path to a spec YAML file.", "#' @return A list with class `cohort_spec`.", 
"read_spec <- function(path) {", "  if (!file.exists(path)) {", 
"    stop(sprintf(\"Spec file not found: %s\", path), call. = FALSE)", 
"  }", "  spec <- yaml::yaml.load_file(path)", "", "  spec$options <- utils::modifyList(", 
"    list(missingness_threshold = 0.60, min_complete_cases = 30L),", 
"    spec$options %||% list()", "  )", "  spec$na_strings <- spec$na_strings %||% c(\"\", \"Unknown\", \"N/A\", \"NA\")", 
"  spec$checks     <- spec$checks %||% list()", "  spec$variables  <- spec$variables %||% list()", 
"", "  for (f in c(\"outcome\", \"filter\", \"record_id_column\")) {", 
"    if (is.null(spec[[f]])) {", "      stop(sprintf(\"Spec is missing the required `%s` section.\", f), call. = FALSE)", 
"    }", "  }", "", "  # Normalise each variable, filling in defaults that the YAML may omit.", 
"  spec$variables <- lapply(spec$variables, function(v) {", "    if (is.null(v$name)) {", 
"      stop(\"Every entry under `variables` needs a `name`.\", call. = FALSE)", 
"    }", "    v$type     <- v$type %||% \"numeric\"", "    v$label    <- v$label %||% v$name", 
"    v$domain   <- v$domain %||% \"Other\"", "    v$required <- isTRUE(v$required)", 
"", "    if (!v$type %in% c(\"numeric\", \"factor\", \"binary\", \"ordinal\", \"derived\")) {", 
"      stop(sprintf(\"Variable `%s` has unknown type `%s`.\", v$name, v$type),", 
"           call. = FALSE)", "    }", "    if (v$type == \"derived\") {", 
"      if (is.null(v$expr) && is.null(v$fn)) {", "        stop(sprintf(\"Derived variable `%s` needs either `expr` or `fn`.\", v$name),", 
"             call. = FALSE)", "      }", "    } else if (is.null(v$source)) {", 
"      stop(sprintf(\"Variable `%s` is type `%s` and needs a `source` column.\",", 
"                   v$name, v$type), call. = FALSE)", "    }", 
"    if (v$type == \"binary\") v$levels <- v$levels %||% c(\"No\", \"Yes\")", 
"", "    # YAML 1.1 reads bare No/Yes/On/Off as booleans, which turns a declared", 
"    # level list into TRUE/FALSE and makes every real value look undeclared.", 
"    # It is a silent, total data loss, so name it precisely.", 
"    if (!is.null(v$levels)) {", "      lv <- unlist(v$levels)", 
"      if (is.logical(lv)) {", "        stop(sprintf('Variable `%s`: `levels` was read as true/false. YAML treats bare No and Yes as booleans -- quote them, e.g. levels: [\"No\", \"Yes\"].',", 
"                     v$name), call. = FALSE)", "      }", "      v$levels <- as.character(lv)", 
"    }", "    if (!is.null(v$recode)) {", "      if (any(vapply(v$recode, is.logical, logical(1)))) {", 
"        stop(sprintf('Variable `%s`: a `recode` value was read as true/false. Quote bare No and Yes in YAML.',", 
"                     v$name), call. = FALSE)", "      }", "    }", 
"    if (v$type == \"ordinal\" && is.null(v$scores)) {", "      stop(sprintf(\"Ordinal variable `%s` needs a `scores` map.\", v$name),", 
"           call. = FALSE)", "    }", "    v", "  })", "", "  nms <- vapply(spec$variables, `[[`, character(1), \"name\")", 
"  if (anyDuplicated(nms)) {", "    stop(sprintf(\"Duplicate variable names in spec: %s\",", 
"                 paste(unique(nms[duplicated(nms)]), collapse = \", \")),", 
"         call. = FALSE)", "  }", "  if (spec$outcome$name %in% nms) {", 
"    stop(sprintf(\"`%s` is both the outcome and a variable; give one a new name.\",", 
"                 spec$outcome$name), call. = FALSE)", "  }", 
"", "  spec$domains <- spec$domains %||% unique(", "    vapply(spec$variables, `[[`, character(1), \"domain\"))", 
"", "  structure(spec, class = c(\"cohort_spec\", \"list\"))", 
"}", "", "#' Variables in a spec, optionally filtered.", "#'", 
"#' @param spec A `cohort_spec`.", "#' @param type Optional character vector of types to keep.", 
"#' @param domain Optional domain to keep.", "spec_variables <- function(spec, type = NULL, domain = NULL) {", 
"  v <- spec$variables", "  if (!is.null(type)) {", "    v <- Filter(function(x) x$type %in% type, v)", 
"  }", "  if (!is.null(domain)) {", "    v <- Filter(function(x) identical(x$domain, domain), v)", 
"  }", "  v", "}", "", "#' Look up a single variable definition by name.", 
"spec_variable <- function(spec, name) {", "  for (v in spec$variables) if (identical(v$name, name)) return(v)", 
"  NULL", "}", "", "#' Resolve a spec `source` string against real export column names.", 
"#'", "#' Exact match wins outright. Failing that, a substring match is accepted only", 
"#' if it is unique — a substring hitting several columns is an error, never a", 
"#' first-match-wins guess, because that is precisely how the original report", 
"#' silently attached itself to the wrong column.", "#'", "#' @param source The `source` string from the spec.", 
"#' @param columns Character vector of column names in the export.", 
"#' @return A list with `status` (\"ok\", \"missing\" or \"ambiguous\"), the matched", 
"#'   `column` when status is \"ok\", and `candidates` when ambiguous.", 
"match_column <- function(source, columns) {", "  if (source %in% columns) {", 
"    return(list(status = \"ok\", column = source, candidates = source))", 
"  }", "  hits <- columns[startsWith(columns, source)]", "  if (length(hits) != 1L) {", 
"    contains <- columns[vapply(columns, function(x)", "      grepl(source, x, fixed = TRUE), logical(1))]", 
"    # Prefer a unique prefix match; fall back to a unique substring match.", 
"    hits <- if (length(hits) > 1L) hits else contains", "  }", 
"  if (length(hits) == 1L) {", "    list(status = \"ok\", column = hits, candidates = hits)", 
"  } else if (length(hits) == 0L) {", "    list(status = \"missing\", column = NA_character_, candidates = character(0))", 
"  } else {", "    list(status = \"ambiguous\", column = NA_character_, candidates = hits)", 
"  }", "}", "", "`%||%` <- function(x, y) if (is.null(x)) y else x"
)

# ==== R/tables.R (454 lines) ====
.embedded[["R/tables.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# Table builders. Everything returns a flextable, because the output formats", 
"# are DOCX and PDF. gt is HTML-first and must not appear here.", 
"#", "# The statistical conventions are the original report's and are deliberate:", 
"#   continuous   median [IQR] and mean (SD), Wilcoxon rank-sum", 
"#   categorical  n (%) to one decimal, chi-square, Fisher when a cell is thin", 
"#   univariate   logistic regression, odds ratio with a Wald 95% CI", 
"# ---------------------------------------------------------------------------", 
"", "# --- small formatting helpers ----------------------------------------------", 
"", "fmt_p <- function(p) {", "  ifelse(is.na(p), \"-\",", "         ifelse(p < 0.001, \"<0.001\", formatC(p, format = \"f\", digits = 3)))", 
"}", "", "fmt_est <- function(x) formatC(x, format = \"f\", digits = 2)", 
"", "# Which outcome level counts as the event.", "outcome_levels <- function(spec) {", 
"  lv <- unname(unlist(spec$outcome$labels))", "  if (is.null(lv) || length(lv) < 2) lv <- c(\"0\", \"1\")", 
"  lv", "}", "", "# Short name for the event, for table titles: \"Demographics by HMB status\"", 
"# reads better than the full outcome label or the bare variable name.", 
"outcome_positive_label <- function(spec) {", "  lv <- outcome_levels(spec)", 
"  lv[[length(lv)]]", "}", "", "#' Standard theme so every table in the report looks the same in Word.", 
"style_table <- function(ft, title = NULL, subtitle = NULL) {", 
"  ft <- flextable::theme_booktabs(ft)", "  # Pin the face explicitly: without it the HTML render falls back to the", 
"  # browser's serif default, so tables came out in Times inside a sans page.", 
"  ft <- flextable::font(ft, fontname = \"Arial\", part = \"all\")", 
"  ft <- flextable::fontsize(ft, size = 9, part = \"all\")", 
"  ft <- flextable::bold(ft, part = \"header\")", "  ft <- flextable::padding(ft, padding.top = 2, padding.bottom = 2, part = \"all\")", 
"  if (!is.null(title)) {", "    ft <- flextable::add_header_lines(ft, values = title)", 
"    ft <- flextable::bold(ft, i = 1, part = \"header\")", "  }", 
"  if (!is.null(subtitle)) {", "    ft <- flextable::add_footer_lines(ft, values = subtitle)", 
"    ft <- flextable::fontsize(ft, size = 8, part = \"footer\")", 
"    ft <- flextable::italic(ft, part = \"footer\")", "  }", 
"  ft <- flextable::align(ft, j = 1, align = \"left\", part = \"all\")", 
"  ft <- flextable::autofit(ft)", "", "  # autofit() sizes columns to their content with no page cap, and the wider", 
"  # summary tables come out at up to twice the printable width -- Word then", 
"  # clips both edges. Scale the columns down proportionally so every table", 
"  # fits the 6.5 in text column of a letter page with 1 in margins, keeping", 
"  # autofit's relative proportions. Scale the widths autofit actually set", 
"  # (dim), not the dim_pretty estimate: autofit pads each column, so the two", 
"  # disagree by enough to leave the widest tables still overflowing.", 
"  # Target a hair under the 6.5 in text column so per-column twip rounding", 
"  # cannot nudge the grid back over the page edge.", "  page_w <- 6.49", 
"  min_w  <- 0.7   # narrower columns wrap \"<0.001\" and \"p-value\" mid-token", 
"  widths <- dim(ft)$widths", "  if (sum(widths) > page_w) {", 
"    widths <- widths * (page_w / sum(widths))", "    if (min_w * length(widths) < page_w && any(widths < min_w)) {", 
"      deficit <- sum(pmax(0, min_w - widths))", "      slack   <- pmax(0, widths - min_w)", 
"      widths  <- pmax(widths, min_w) - deficit * slack / sum(slack)", 
"    }", "    ft <- flextable::width(ft, width = widths)", "  }", 
"  ft", "}", "", "# --- significance testing ---------------------------------------------------", 
"", "#' Chi-square with a Fisher fallback, or Wilcoxon for continuous variables.", 
"#'", "#' Supplied to gtsummary as a custom test so the report's p-values follow the", 
"#' original conventions rather than gtsummary's defaults.", 
"cohort_test <- function(data, variable, by, ...) {", "  x <- data[[variable]]", 
"  g <- data[[by]]", "  keep <- !is.na(x) & !is.na(g)", "  x <- x[keep]", 
"  g <- droplevels(as.factor(g[keep]))", "", "  none <- dplyr::tibble(p.value = NA_real_, method = \"not tested\")", 
"  if (nlevels(g) < 2L || length(x) < 3L) return(none)", "", 
"  if (is.numeric(x)) {", "    if (stats::sd(x, na.rm = TRUE) == 0) return(none)", 
"    p <- suppressWarnings(stats::wilcox.test(x ~ g)$p.value)", 
"    return(dplyr::tibble(p.value = p, method = \"Wilcoxon rank-sum\"))", 
"  }", "", "  tab <- table(droplevels(as.factor(x)), g)", "  if (nrow(tab) < 2L || ncol(tab) < 2L) return(none)", 
"", "  expected <- suppressWarnings(stats::chisq.test(tab)$expected)", 
"  if (any(expected < 5)) {", "    # Simulated rather than exact: some of these tables are large enough that", 
"    # the exact computation will not finish.", "    p <- stats::fisher.test(tab, simulate.p.value = TRUE, B = 10000)$p.value", 
"    dplyr::tibble(p.value = p, method = \"Fisher's exact (simulated)\")", 
"  } else {", "    p <- stats::chisq.test(tab, correct = FALSE)$p.value", 
"    dplyr::tibble(p.value = p, method = \"Pearson chi-square\")", 
"  }", "}", "", "# --- descriptive tables -----------------------------------------------------", 
"", "#' Variables from one domain that actually made it into the analysis frame.", 
"domain_vars <- function(data, spec, domain) {", "  v <- spec_variables(spec, domain = domain)", 
"  nms <- vapply(v, `[[`, character(1), \"name\")", "  nms[nms %in% names(data)]", 
"}", "", "#' Attach spec labels so gtsummary prints human wording, not variable names.", 
"label_columns <- function(data, spec) {", "  for (nm in names(data)) {", 
"    v <- spec_variable(spec, nm)", "    lab <- if (!is.null(v)) v$label else if (identical(nm, spec$outcome$name))", 
"      spec$outcome$label else nm", "    attr(data[[nm]], \"label\") <- lab", 
"  }", "  data", "}", "", "#' Descriptive table for one domain, split by the outcome.", 
"#'", "#' @return A flextable, or NULL if the domain has nothing to show.", 
"descriptive_flextable <- function(data, spec, domain, title = NULL) {", 
"  vars <- domain_vars(data, spec, domain)", "  # A variable that is missing for everyone has nothing to describe; it is", 
"  # already reported in the missingness section.", "  vars <- vars[vapply(vars, function(nm) any(!is.na(data[[nm]])), logical(1))]", 
"  if (!length(vars)) return(NULL)", "", "  y <- spec$outcome$name", 
"  d <- data[, c(vars, y), drop = FALSE]", "  d <- d[!is.na(d[[y]]), , drop = FALSE]", 
"  # Label last: subsetting rows of a data.frame drops column attributes, so", 
"  # labelling before this point silently leaves gtsummary printing raw names.", 
"  d <- label_columns(d, spec)", "", "  # gtsummary infers continuous vs categorical from how many distinct values a", 
"  # column has, which turns a 0-4 ordinal score into five percentage rows. The", 
"  # spec declares the type, so the spec decides.", "  is_continuous <- vapply(vars, function(nm) {", 
"    v <- spec_variable(spec, nm)", "    !is.null(v) && v$type %in% c(\"numeric\", \"ordinal\", \"derived\")", 
"  }, logical(1))", "  cont <- vars[is_continuous]", "  catg <- vars[!is_continuous]", 
"", "  type_arg <- c(", "    if (length(cont)) list(dplyr::all_of(cont) ~ \"continuous\"),", 
"    if (length(catg)) list(dplyr::all_of(catg) ~ \"categorical\")", 
"  )", "", "  tbl <- gtsummary::tbl_summary(", "    d,", "    by = dplyr::all_of(y),", 
"    type = type_arg,", "    statistic = list(", "      gtsummary::all_continuous()  ~ \"{median} [{p25}, {p75}]; {mean} ({sd})\",", 
"      gtsummary::all_categorical() ~ \"{n} ({p}%)\"", "    ),", 
"    # One decimal throughout, as in the original report: \"17.0 [16.0, 18.0];", 
"    # 16.8 (1.8)\". gtsummary's adaptive digits produce up to four decimals for", 
"    # small-scale variables, which both reads badly and widens the cells past", 
"    # the page.", "    digits = list(", "      gtsummary::all_continuous()  ~ 1,", 
"      gtsummary::all_categorical() ~ c(0, 1)", "    ),", "    missing = \"no\"", 
"  )", "  tbl <- gtsummary::add_overall(tbl, last = FALSE)", 
"  tbl <- gtsummary::add_p(tbl, test = gtsummary::everything() ~ cohort_test,", 
"                          pvalue_fun = function(x) fmt_p(x))", 
"  tbl <- gtsummary::modify_header(tbl, label = \"**Variable**\")", 
"", "  ft <- gtsummary::as_flex_table(tbl)", "  style_table(ft, title = title,", 
"              subtitle = paste(\"Continuous: median [IQR]; mean (SD), Wilcoxon rank-sum.\",", 
"                               \"Categorical: n (%), chi-square or Fisher's exact.\"))", 
"}", "", "# --- univariate logistic regression ----------------------------------------", 
"", "#' Fit one unadjusted logistic model and return tidy rows.", 
"#'", "#' Returns a `note` instead of estimates when the model cannot be trusted.", 
"#' Several VITAL-HMB variables separate the outcome perfectly; fitting them", 
"#' anyway yields an odds ratio around 10^8, which reads as a finding rather", 
"#' than as an artefact.", "univariate_fit <- function(data, spec, varname) {", 
"  y_name <- spec$outcome$name", "  lv <- levels(data[[y_name]])", 
"  if (is.null(lv)) lv <- outcome_levels(spec)", "  y <- as.integer(data[[y_name]] == lv[length(lv)])", 
"  x <- data[[varname]]", "  v <- spec_variable(spec, varname)", 
"  label <- if (!is.null(v)) v$label else varname", "", "  keep <- !is.na(y) & !is.na(x)", 
"  n <- sum(keep)", "  none <- function(note) data.frame(", "    variable = varname, label = label, term = label, or = NA_real_,", 
"    lcl = NA_real_, ucl = NA_real_, p = NA_real_, n = n, note = note,", 
"    stringsAsFactors = FALSE)", "", "  if (n < (spec$options$min_complete_cases %||% 30L)) {", 
"    return(none(sprintf(\"not estimable: %d complete cases\", n)))", 
"  }", "  yy <- y[keep]", "  xx <- x[keep]", "  if (length(unique(yy)) < 2L) return(none(\"not estimable: outcome has one level\"))", 
"", "  if (is.numeric(xx)) {", "    if (stats::sd(xx) == 0) return(none(\"not estimable: no variation\"))", 
"  } else {", "    xx <- droplevels(as.factor(xx))", "    if (nlevels(xx) < 2L) return(none(\"not estimable: only one category present\"))", 
"    tab <- table(xx, yy)", "    if (any(tab == 0)) {", "      # A zero cell means at least one category perfectly predicts the outcome.", 
"      return(none(\"not estimable: outcome perfectly separated\"))", 
"    }", "  }", "", "  fit <- tryCatch(", "    suppressWarnings(stats::glm(yy ~ xx, family = stats::binomial())),", 
"    error = function(e) NULL)", "  if (is.null(fit) || !fit$converged) return(none(\"not estimable: model did not converge\"))", 
"", "  co <- summary(fit)$coefficients", "  co <- co[rownames(co) != \"(Intercept)\", , drop = FALSE]", 
"  if (!nrow(co)) return(none(\"not estimable: no estimable terms\"))", 
"", "  # Huge coefficients or standard errors are the signature of separation that", 
"  # slipped past the zero-cell check.", "  if (any(abs(co[, 1]) > 10) || any(co[, 2] > 10)) {", 
"    return(none(\"not estimable: outcome perfectly separated\"))", 
"  }", "", "  est <- co[, 1]; se <- co[, 2]; p <- co[, 4]", "  terms <- rownames(co)", 
"  terms <- sub(\"^xx\", \"\", terms)", "  terms <- if (is.numeric(x)) rep(label, length(terms)) else paste0(label, \": \", terms)", 
"", "  data.frame(", "    variable = varname, label = label, term = terms,", 
"    or = exp(est), lcl = exp(est - 1.96 * se), ucl = exp(est + 1.96 * se),", 
"    p = p, n = n, note = \"\", stringsAsFactors = FALSE, row.names = NULL)", 
"}", "", "#' Univariate associations across a set of domains.", 
"univariate_results <- function(data, spec, domains) {", "  vars <- unlist(lapply(domains, function(dm) domain_vars(data, spec, dm)))", 
"  if (!length(vars)) return(NULL)", "  out <- lapply(vars, function(nm) univariate_fit(data, spec, nm))", 
"  do.call(rbind, out)", "}", "", "#' Render univariate results as a flextable.", 
"univariate_flextable <- function(res, title = NULL) {", "  if (is.null(res) || !nrow(res)) return(NULL)", 
"  disp <- data.frame(", "    Predictor = res$term,", "    OR = ifelse(is.na(res$or), \"-\", fmt_est(res$or)),", 
"    `95% CI` = ifelse(is.na(res$or), \"-\",", "                      sprintf(\"%s - %s\", fmt_est(res$lcl), fmt_est(res$ucl))),", 
"    p = ifelse(is.na(res$p), \"-\", fmt_p(res$p)),", "    Note = res$note,", 
"    check.names = FALSE, stringsAsFactors = FALSE)", "", "  ft <- flextable::flextable(disp)", 
"  ft <- flextable::italic(ft, i = which(nzchar(res$note)), j = 5)", 
"  style_table(ft, title = title,", "              subtitle = \"Unadjusted logistic regression. OR with Wald 95% CI.\")", 
"}", "", "# --- data quality tables ----------------------------------------------------", 
"", "missingness_flextable <- function(quality, spec, top = NULL) {", 
"  m <- quality$missingness", "  if (is.null(m) || !nrow(m)) return(NULL)", 
"  if (!is.null(top)) m <- utils::head(m, top)", "  disp <- data.frame(", 
"    Variable = m$label, Domain = m$domain,", "    `N missing` = m$n_missing, `% missing` = m$pct_missing,", 
"    check.names = FALSE, stringsAsFactors = FALSE)", "  style_table(flextable::flextable(disp), title = \"Missingness by variable\")", 
"}", "", "checks_flextable <- function(quality) {", "  ck <- quality$checks", 
"  if (is.null(ck) || !nrow(ck)) return(NULL)", "  disp <- data.frame(", 
"    Check = ck$check, Evaluable = ck$evaluable,", "    Violations = ck$violations, `% violating` = ck$pct,", 
"    check.names = FALSE, stringsAsFactors = FALSE)", "  style_table(flextable::flextable(disp), title = \"Variable consistency checks\",", 
"              subtitle = \"Records where the rule cannot be evaluated are excluded from the denominator.\")", 
"}", "", "range_flextable <- function(quality) {", "  r <- quality$out_of_range", 
"  if (is.null(r) || !nrow(r)) return(NULL)", "  disp <- data.frame(", 
"    Variable = r$label,", "    `Valid range` = sprintf(\"%s to %s\", r$low, r$high),", 
"    `Values dropped` = r$n,", "    check.names = FALSE, stringsAsFactors = FALSE)", 
"  style_table(flextable::flextable(disp),", "              title = \"Values outside the plausible range\",", 
"              subtitle = \"These were set to missing before analysis.\")", 
"}", "", "levels_flextable <- function(quality) {", "  b <- quality$bad_levels", 
"  if (is.null(b) || !nrow(b)) return(NULL)", "  disp <- data.frame(", 
"    Variable = b$label, Issue = b$issue, Values = b$value, N = b$n,", 
"    check.names = FALSE, stringsAsFactors = FALSE)", "  style_table(flextable::flextable(disp),", 
"              title = \"Responses not declared in the spec\",", 
"              subtitle = \"These were left as missing rather than folded into an existing category.\")", 
"}", "", "# --- missingness mechanism --------------------------------------------------", 
"", "#' Columns that are exact linear combinations of earlier ones.", 
"#'", "#' Little's test inverts a covariance matrix, so a derived variable such as", 
"#' mean arterial pressure -- exactly (sbp + 2*dbp)/3 -- makes it singular and", 
"#' the test fails outright. Rank detection drops the redundant columns instead.", 
"independent_columns <- function(data, vars) {", "  m <- as.matrix(data[, vars, drop = FALSE])", 
"  # Impute to the mean only to detect dependence; an exact linear relationship", 
"  # survives mean imputation, and the imputed copy is not used for anything else.", 
"  for (j in seq_len(ncol(m))) {", "    mu <- mean(m[, j], na.rm = TRUE)", 
"    m[is.na(m[, j]), j] <- mu", "  }", "  m <- scale(m)", "  m[is.na(m)] <- 0", 
"  q <- qr(m)", "  vars[sort(q$pivot[seq_len(q$rank)])]", "}", 
"", "#' Little's MCAR test over numeric variables below the missingness threshold.", 
"mcar_result <- function(data, spec) {", "  thresh <- spec$options$missingness_threshold %||% 0.60", 
"  num <- names(data)[vapply(data, is.numeric, logical(1))]", 
"  num <- num[vapply(num, function(nm) mean(is.na(data[[nm]])) < thresh, logical(1))]", 
"  num <- num[vapply(num, function(nm) stats::sd(data[[nm]], na.rm = TRUE) > 0, logical(1))]", 
"  if (length(num) < 2L) {", "    return(list(ok = FALSE, message = \"Not enough numeric variables to test.\"))", 
"  }", "", "  keep <- independent_columns(data, num)", "  dropped <- setdiff(num, keep)", 
"  if (length(keep) < 2L) {", "    return(list(ok = FALSE,", 
"                message = \"Not enough independent numeric variables to test.\"))", 
"  }", "", "  res <- tryCatch(naniar::mcar_test(data[, keep, drop = FALSE]),", 
"                  error = function(e) NULL)", "  if (is.null(res)) {", 
"    return(list(ok = FALSE,", "                message = \"Little's test could not be computed on these variables.\"))", 
"  }", "  list(ok = TRUE, n_vars = length(keep), dropped = dropped,", 
"       statistic = res$statistic, df = res$df, p.value = res$p.value,", 
"       missing.patterns = res$missing.patterns)", "}", "", "#' Chi-square probe of each variable's missingness against the outcome.", 
"#'", "#' A small p-value says the data are not missing completely at random.", 
"missing_vs_outcome <- function(data, spec) {", "  y <- data[[spec$outcome$name]]", 
"  vars <- setdiff(names(data), c(\".record_id\", spec$outcome$name))", 
"  rows <- lapply(vars, function(nm) {", "    miss <- is.na(data[[nm]])", 
"    if (!any(miss) || all(miss)) return(NULL)", "    tab <- table(miss, y)", 
"    if (nrow(tab) < 2L || ncol(tab) < 2L) return(NULL)", "    p <- tryCatch({", 
"      ex <- suppressWarnings(stats::chisq.test(tab)$expected)", 
"      if (any(ex < 5)) stats::fisher.test(tab)$p.value", "      else stats::chisq.test(tab, correct = FALSE)$p.value", 
"    }, error = function(e) NA_real_)", "    v <- spec_variable(spec, nm)", 
"    data.frame(variable = nm, label = if (!is.null(v)) v$label else nm,", 
"               pct_missing = round(100 * mean(miss), 1), p = p,", 
"               stringsAsFactors = FALSE)", "  })", "  rows <- Filter(Negate(is.null), rows)", 
"  if (!length(rows)) return(NULL)", "  out <- do.call(rbind, rows)", 
"  out[order(out$p), , drop = FALSE]", "}", "", "missing_vs_outcome_flextable <- function(mv) {", 
"  if (is.null(mv) || !nrow(mv)) return(NULL)", "  disp <- data.frame(", 
"    Variable = mv$label, `% missing` = mv$pct_missing, p = fmt_p(mv$p),", 
"    check.names = FALSE, stringsAsFactors = FALSE)", "  style_table(flextable::flextable(disp),", 
"              title = \"Does missingness depend on the outcome?\",", 
"              subtitle = \"A small p-value suggests missingness is related to the outcome (not MCAR).\")", 
"}", "", "# --- plots ------------------------------------------------------------------", 
"", "#' Boxplots of the most strongly associated numeric variables by outcome.", 
"outcome_plots <- function(data, spec, res, max_panels = 6L) {", 
"  if (is.null(res)) return(NULL)", "  num <- vapply(res$variable, function(nm) is.numeric(data[[nm]]), logical(1))", 
"  cand <- res[num & !is.na(res$p), , drop = FALSE]", "  if (!nrow(cand)) return(NULL)", 
"  cand <- cand[order(cand$p), , drop = FALSE]", "  vars <- utils::head(unique(cand$variable), max_panels)", 
"", "  y <- spec$outcome$name", "  long <- do.call(rbind, lapply(vars, function(nm) {", 
"    v <- spec_variable(spec, nm)", "    data.frame(panel = if (!is.null(v)) v$label else nm,", 
"               value = data[[nm]], group = data[[y]],", "               stringsAsFactors = FALSE)", 
"  }))", "  long <- long[!is.na(long$value) & !is.na(long$group), , drop = FALSE]", 
"  if (!nrow(long)) return(NULL)", "", "  ggplot2::ggplot(long, ggplot2::aes(x = group, y = value, fill = group)) +", 
"    ggplot2::geom_boxplot(outlier.size = 0.6, alpha = 0.85) +", 
"    ggplot2::facet_wrap(~panel, scales = \"free_y\") +", "    ggplot2::labs(x = NULL, y = NULL) +", 
"    ggplot2::theme_minimal(base_size = 9) +", "    ggplot2::theme(legend.position = \"none\",", 
"                   strip.text = ggplot2::element_text(face = \"bold\", size = 8))", 
"}")

# ==== R/validate.R (280 lines) ====
.embedded[["R/validate.R"]] <-
c("# ---------------------------------------------------------------------------", 
"# The schema gate.", "#", "# This file exists because the original report matched columns by substring of", 
"# the REDCap label and returned an all-NA column when nothing matched. A whole", 
"# analysis then ran on nothing. Every check below turns one variant of that", 
"# silent failure into a loud one.", "#", "# Two severities:", 
"#   hard  the render cannot proceed; report every problem at once, never stop", 
"#         at the first one, because staff re-export once and want the full list", 
"#   soft  the render proceeds and the problem is surfaced in data quality", 
"# ---------------------------------------------------------------------------", 
"", "#' Read a REDCap label export.", "#'", "#' REDCap label exports are ISO-8859-1. Reading one as UTF-8 does not error; it", 
"#' silently mangles any non-ASCII header, after which every column lookup", 
"#' misses and the analytic sample comes back empty.", "#'", 
"#' @param path Path to the CSV.", "#' @return A data.frame, all columns character, names unmodified.", 
"read_export <- function(path, encoding = \"ISO-8859-1\") {", 
"  if (!file.exists(path)) {", "    stop(sprintf(\"Data file not found: %s\", path), call. = FALSE)", 
"  }", "  out <- readr::read_csv(", "    path,", "    col_types = readr::cols(.default = readr::col_character()),", 
"    locale    = readr::locale(encoding = encoding),", "    na        = character(),          # keep blanks; na_strings handles them", 
"    progress  = FALSE,", "    name_repair = \"minimal\"", "  )", 
"  as.data.frame(out, check.names = FALSE, stringsAsFactors = FALSE)", 
"}", "", "fail <- function(code, message, detail = NULL) {", 
"  list(code = code, message = message, detail = detail)", "}", 
"", "# Does this export look like it came out of REDCap with raw values rather than", 
"# labels? Raw exports use lowercase snake_case field names with no spaces.", 
"looks_like_raw_export <- function(columns) {", "  if (!length(columns)) return(FALSE)", 
"  snakey <- grepl(\"^[a-z][a-z0-9_]*$\", columns)", "  mean(snakey) > 0.8", 
"}", "", "#' Validate an export against a spec.", "#'", "#' @param raw A data.frame as returned by [read_export()].", 
"#' @param spec A `cohort_spec` from [read_spec()].", "#' @return An object of class `cohort_validation`.", 
"validate_export <- function(raw, spec) {", "  hard <- list()", 
"  soft <- list()", "  cols <- names(raw)", "", "  # --- structural columns --------------------------------------------------", 
"", "  structural <- list(", "    record_id = spec$record_id_column,", 
"    event     = spec$filter$event_column,", "    outcome   = spec$outcome$source", 
"  )", "  resolved_structural <- list()", "", "  for (key in names(structural)) {", 
"    src <- structural[[key]]", "    m <- match_column(src, cols)", 
"    resolved_structural[[key]] <- m$column", "    if (m$status == \"missing\") {", 
"      msg <- sprintf('Column \"%s\" not found in the upload.', src)", 
"      if (key == \"outcome\" && looks_like_raw_export(cols)) {", 
"        msg <- paste(msg, \"This looks like a raw-value export -- re-export from\",", 
"                     \"REDCap with labels.\")", "      } else {", 
"        msg <- paste(msg, \"Check that this is the right file and that the\",", 
"                     \"column has not been renamed.\")", "      }", 
"      hard <- c(hard, list(fail(paste0(\"missing_\", key), msg)))", 
"    } else if (m$status == \"ambiguous\") {", "      hard <- c(hard, list(fail(", 
"        paste0(\"ambiguous_\", key),", "        sprintf('Column \"%s\" matches %d columns, so we cannot tell which one is meant: %s',", 
"                src, length(m$candidates), paste(sprintf('\"%s\"', m$candidates), collapse = \", \")),", 
"        m$candidates)))", "    }", "  }", "", "  # --- variable source columns --------------------------------------------", 
"", "  mapping   <- character(0)", "  unmatched <- character(0)", 
"", "  for (v in spec_variables(spec)) {", "    if (v$type == \"derived\") next", 
"    m <- match_column(v$source, cols)", "    if (m$status == \"ok\") {", 
"      mapping[[v$name]] <- m$column", "    } else if (m$status == \"ambiguous\") {", 
"      # Ambiguity is always hard: picking the first match is the bug this", 
"      # repo was built to prevent.", "      hard <- c(hard, list(fail(", 
"        \"ambiguous_column\",", "        sprintf('Variable \"%s\": the text \"%s\" matches %d columns, so we cannot tell which one is meant: %s',", 
"                v$label, v$source, length(m$candidates),", "                paste(sprintf('\"%s\"', m$candidates), collapse = \", \")),", 
"        m$candidates)))", "    } else if (v$required) {", "      hard <- c(hard, list(fail(", 
"        \"missing_required\",", "        sprintf('Required variable \"%s\" needs a column matching \"%s\", which is not in the upload.',", 
"                v$label, v$source))))", "    } else {", "      unmatched <- c(unmatched, v$name)", 
"      soft <- c(soft, list(fail(", "        \"missing_optional\",", 
"        sprintf('Optional variable \"%s\" (looking for \"%s\") is not in the upload and will be left out of the report.',", 
"                v$label, v$source))))", "    }", "  }", "", 
"  # Derived variables that name explicit source columns must find them too.", 
"  for (v in spec_variables(spec, type = \"derived\")) {", "    if (is.null(v$args)) next", 
"    if (!is.null(v$args$columns)) {", "      miss <- character(0)", 
"      for (cn in v$args$columns) {", "        if (match_column(cn, cols)$status != \"ok\") miss <- c(miss, cn)", 
"      }", "      if (length(miss)) {", "        soft <- c(soft, list(fail(", 
"          \"missing_derived_input\",", "          sprintf('Derived variable \"%s\" is missing %d of its %d input columns (%s); it will be computed from the rest.',", 
"                  v$label, length(miss), length(v$args$columns),", 
"                  paste(sprintf('\"%s\"', utils::head(miss, 5)), collapse = \", \")),", 
"          miss)))", "      }", "    }", "    if (!is.null(v$args$pattern) && !is.null(v$args$n_items)) {", 
"      found <- sum(grepl(v$args$pattern, cols))", "      if (found != v$args$n_items) {", 
"        # A changed item count silently rescales the score, so this is hard.", 
"        hard <- c(hard, list(fail(", "          \"item_count_mismatch\",", 
"          sprintf('Derived variable \"%s\" expects %d items matching %s but the upload has %d. The questionnaire appears to have changed; update the spec before reporting a score.',", 
"                  v$label, v$args$n_items, v$args$pattern, found))))", 
"      }", "    }", "  }", "", "  # Anything in the export the spec never mentions: informational only.", 
"  claimed <- unname(mapping)", "  known   <- c(claimed, unlist(resolved_structural, use.names = FALSE))", 
"  for (v in spec_variables(spec, type = \"derived\")) {", "    if (!is.null(v$args$columns)) {", 
"      known <- c(known, vapply(v$args$columns, function(cn)", 
"        match_column(cn, cols)$column, character(1)))", "    }", 
"    if (!is.null(v$args$pattern)) known <- c(known, cols[grepl(v$args$pattern, cols)])", 
"  }", "  extra <- setdiff(cols, stats::na.omit(known))", "", 
"  # --- row-level structure -------------------------------------------------", 
"", "  rows <- rep(TRUE, nrow(raw))", "  n_analytic <- NA_integer_", 
"  outcome_col <- resolved_structural$outcome", "", "  if (!is.na(outcome_col)) {", 
"    y_raw <- clean_values(raw[[outcome_col]], spec$na_strings)", 
"    if (all(is.na(y_raw))) {", "      hard <- c(hard, list(fail(", 
"        \"outcome_all_missing\",", "        sprintf('The outcome column \"%s\" is present but empty for every row. No participant has a result to analyse.',", 
"                outcome_col))))", "    }", "    rows <- rows & !is.na(y_raw)", 
"  }", "", "  event_col <- resolved_structural$event", "  if (!is.na(event_col)) {", 
"    want <- spec$filter$event_value", "    ev   <- trimws(as.character(raw[[event_col]]))", 
"    keep <- !is.na(ev) & ev == want", "    if (!any(keep)) {", 
"      hard <- c(hard, list(fail(", "        \"no_matching_event\",", 
"        sprintf('No rows have \"%s\" in the \"%s\" column. Values present are: %s',", 
"                want, event_col,", "                paste(sprintf('\"%s\"', utils::head(unique(stats::na.omit(ev)), 8)),", 
"                      collapse = \", \")))))", "    }", "    rows <- rows & keep", 
"  }", "", "  for (src in spec$filter$require_nonmissing %||% character(0)) {", 
"    m <- match_column(src, cols)", "    if (m$status == \"ok\") {", 
"      rows <- rows & !is.na(clean_values(raw[[m$column]], spec$na_strings))", 
"    }", "  }", "", "  if (!any(rows)) {", "    # Only worth saying if we did not already say something more specific.", 
"    if (!length(Filter(function(f) f$code %in%", "                       c(\"no_matching_event\", \"outcome_all_missing\"), hard))) {", 
"      hard <- c(hard, list(fail(", "        \"empty_analytic_sample\",", 
"        \"No participants are left after applying the event filter and requiring an outcome result. Check that the export covers the right visit.\")))", 
"    }", "  } else {", "    n_analytic <- sum(rows)", "  }", 
"", "  # --- duplicate record IDs ------------------------------------------------", 
"", "  id_col <- resolved_structural$record_id", "  if (!is.na(id_col) && any(rows)) {", 
"    ids <- as.character(raw[[id_col]][rows])", "    dup <- unique(ids[duplicated(ids)])", 
"    if (length(dup)) {", "      hard <- c(hard, list(fail(", 
"        \"duplicate_ids\",", "        sprintf('%d participant ID%s appear%s more than once in the analysis sample: %s. Each participant must appear exactly once.',", 
"                length(dup), if (length(dup) == 1) \"\" else \"s\",", 
"                if (length(dup) == 1) \"s\" else \"\",", "                paste(utils::head(dup, 10), collapse = \", \")),", 
"        dup)))", "    }", "  }", "", "  structure(", "    list(", 
"      ok          = length(hard) == 0L,", "      hard        = hard,", 
"      soft        = soft,", "      columns     = mapping,", 
"      structural  = resolved_structural,", "      unmatched   = unmatched,", 
"      unused      = extra,", "      rows        = rows,", "      n_rows      = nrow(raw),", 
"      n_analytic  = n_analytic,", "      spec        = spec", 
"    ),", "    class = c(\"cohort_validation\", \"list\")", "  )", 
"}", "", "#' Abort with the full list of hard failures, formatted for a human reader.", 
"stop_if_invalid <- function(validation) {", "  if (validation$ok) return(invisible(validation))", 
"  msgs <- vapply(validation$hard, `[[`, character(1), \"message\")", 
"  stop(paste0(", "    \"This export cannot be analysed yet. \",", 
"    length(msgs), if (length(msgs) == 1) \" problem\" else \" problems\",", 
"    \" found:\\n\\n\",", "    paste0(\"  \", seq_along(msgs), \". \", msgs, collapse = \"\\n\\n\"),", 
"    \"\\n\"), call. = FALSE)", "}", "", "#' @export", "print.cohort_validation <- function(x, ...) {", 
"  cat(sprintf(\"<cohort_validation> %s\\n\", if (x$ok) \"PASSED\" else \"FAILED\"))", 
"  cat(sprintf(\"  rows in file:      %d\\n\", x$n_rows))", "  cat(sprintf(\"  analytic sample:   %s\\n\",", 
"              if (is.na(x$n_analytic)) \"-\" else format(x$n_analytic)))", 
"  cat(sprintf(\"  columns matched:   %d\\n\", length(x$columns)))", 
"  if (length(x$hard)) {", "    cat(\"  hard failures:\\n\")", 
"    for (f in x$hard) cat(sprintf(\"    - %s\\n\", f$message))", 
"  }", "  if (length(x$soft)) {", "    cat(sprintf(\"  soft findings:     %d\\n\", length(x$soft)))", 
"  }", "  invisible(x)", "}")

# ==== spec/vital-hmb.yaml (602 lines) ====
.embedded[["spec/vital-hmb.yaml"]] <-
c("# ---------------------------------------------------------------------------", 
"# VITAL-HMB study spec", "#", "# Outcome: heavy menstrual bleeding (HMB) by alkaline hematin.", 
"#", "# This file is the single source of truth for every variable the report shows.", 
"# Adding a variable to the report means adding it here and nowhere else.", 
"#", "# `source` is matched against export column names: exact match first, then", 
"# unique substring. A substring that matches more than one column is an error.", 
"# ---------------------------------------------------------------------------", 
"", "study: VITAL-HMB", "title: Descriptive and Univariate Analysis", 
"", "record_id_column: Record ID", "", "outcome:", "  name: hmb", 
"  source: HMB calc", "  label: Heavy menstrual bleeding (alkaline hematin)", 
"  type: binary", "  # Keys are the values found in the export; order sets the reference level.", 
"  labels:", "    0: Non-HMB", "    1: HMB", "", "filter:", "  event_column: Event Name", 
"  event_value: Baseline", "  require_nonmissing: [HMB calc]", 
"", "# Values treated as missing wherever they appear. The REDCap export writes", 
"# these into otherwise-categorical columns; folding them into a factor level", 
"# would invent a category that no one answered.", "na_strings: [\"\", \"Unknown\", \"Don't know\", \"Prefer not to say\", \"N/A\", \"NA\", \".\"]", 
"", "options:", "  # A variable missing more than this fraction is flagged in data quality.", 
"  missingness_threshold: 0.60", "  # Univariate models below this many complete cases are non-estimable.", 
"  min_complete_cases: 30", "", "# Display order for the descriptive tables.", 
"domains:", "  - Demographics", "  - Social history", "  - Obstetrics & gynaecology", 
"  - Medical history", "  - Clinical measurements", "  - Ultrasound", 
"  - Laboratory", "  - Mental health & QoL", "", "variables:", 
"", "  # --- Demographics --------------------------------------------------------", 
"", "  - name: age", "    source: agecalc", "    domain: Demographics", 
"    label: Age (years)", "    type: numeric", "    range: [12, 45]", 
"    required: true", "", "  - name: region", "    source: B1. Which region", 
"    domain: Demographics", "    label: Region", "    type: factor", 
"    levels: [Central, Eastern, Northern, Western, Other]", "    required: true", 
"", "  - name: residence", "    source: B2. In what type of environment", 
"    domain: Demographics", "    label: Residence", "    type: factor", 
"    levels: [Rural, Semi-urban, Urban]", "    required: true", 
"", "  - name: marital", "    source: B3. What is your marital status", 
"    domain: Demographics", "    label: Marital status", "    type: factor", 
"    levels: [Ever-married, Single]", "    # Cell counts for the individual ever-married states are too small to", 
"    # report separately; the original collapsed them and so do we, explicitly.", 
"    recode:", "      Married: Ever-married", "      Separated: Ever-married", 
"      Divorced: Ever-married", "      Widowed: Ever-married", 
"    required: true", "", "  - name: in_school", "    source: B4. Are you currently in school", 
"    domain: Demographics", "    label: Currently in school", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "    required: true", 
"", "  - name: education", "    source: B5. What is your highest level of education", 
"    domain: Demographics", "    label: Education", "    type: factor", 
"    levels: [Secondary, Tertiary]", "    required: true", "", 
"  - name: religion", "    source: B6. What is your religious", 
"    domain: Demographics", "    label: Religion", "    type: factor", 
"    levels: [Anglican, Catholic, Muslim, Pentecostal, Other]", 
"    recode:", "      Moslem: Muslim", "    required: true", 
"", "  - name: ses_index", "    domain: Demographics", "    label: Socioeconomic status (PCA)", 
"    type: derived", "    fn: asset_pca", "    # Explicit column list, never a regex. The original matched asset columns", 
"    # by pattern, so adding a checkbox to the form silently redefined the index.", 
"    args:", "      positive: [Checked, Yes]", "      columns:", 
"        - Radio", "        - Television", "        - Bicycle", 
"        - Motor cycle", "        - Computer", "        - Tablet", 
"        - Business", "        - Bathroom", "        - Running water", 
"        - Electricity", "        - Solar", "        - Car", 
"        - Generator", "        - Mattress", "        - Bed with mattress", 
"        - Cupboard", "        - Truck", "        - Microwave", 
"        - Dining table", "        - Family home", "        - Smartphone", 
"", "  # --- Social history ------------------------------------------------------", 
"", "  - name: smoking", "    source: D1. Do you currently smoke", 
"    domain: Social history", "    label: Smoking", "    type: factor", 
"    levels: [Ever, Never]", "    recode:", "      Never smoked: Never", 
"      \"Yes, occasionally\": Ever", "      \"Yes, daily\": Ever", 
"    required: true", "", "  - name: alcohol", "    source: D9. Which of the following best describes", 
"    domain: Social history", "    label: Alcohol use", "    type: factor", 
"    levels: [Ever, Never]", "    recode:", "      Never drink alcohol: Never", 
"      Drink occasionally: Ever", "      Drink weekly: Ever", 
"      Drink daily: Ever", "    required: true", "", "  - name: water_source", 
"    source: B11. What is the main source of drinking water", 
"    domain: Social history", "    label: Drinking water source", 
"    type: factor", "    levels: [Borehole, Piped water, Other]", 
"    recode:", "      Protected spring: Other", "      Surface water: Other", 
"      Unprotected spring: Other", "      Rain water: Other", 
"    required: true", "", "  - name: cooking_fuel", "    source: B16. What is the main source of energy", 
"    domain: Social history", "    label: Cooking fuel", "    type: factor", 
"    levels: [Charcoal, Fire wood, Other]", "    recode:", "      Gas: Other", 
"      Electricity for cooking: Other", "      Paraffin: Other", 
"    required: true", "", "  - name: financial", "    source: B9. How well would you say you are managing", 
"    domain: Social history", "    label: Financial difficulty (0-4)", 
"    # Ordinal: reported as a score, ascending in difficulty.", 
"    type: ordinal", "    levels:", "      - Living comfortably", 
"      - Doing alright", "      - Just getting by", "      - Finding it quite difficult", 
"      - Finding it very difficult", "    scores:", "      Living comfortably: 0", 
"      Doing alright: 1", "      Just getting by: 2", "      Finding it quite difficult: 3", 
"      Finding it very difficult: 4", "    required: true", "", 
"  # --- Obstetrics & gynaecology --------------------------------------------", 
"", "  - name: age_menarche", "    source: E1. At what age did you start", 
"    domain: Obstetrics & gynaecology", "    label: Age at menarche", 
"    type: numeric", "    range: [8, 20]", "    required: true", 
"", "  - name: cycle_length", "    source: E3. How long was your previous menstrual cycle", 
"    domain: Obstetrics & gynaecology", "    label: Cycle length (days)", 
"    type: numeric", "    range: [15, 60]", "    required: true", 
"", "  - name: regular", "    source: E4. During the last 6 months, did you have menstrual periods every month", 
"    domain: Obstetrics & gynaecology", "    label: Regular monthly periods", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "    required: true", 
"", "  - name: bleeding_days", "    source: E6. During the last 6 months, on average, how many days did you spend actively bleeding", 
"    domain: Obstetrics & gynaecology", "    label: Active bleeding days/cycle", 
"    type: numeric", "    range: [1, 30]", "    required: true", 
"", "  - name: intermens", "    source: E7. During the last 6 months, how many days do you experience on average in between", 
"    domain: Obstetrics & gynaecology", "    label: Days between periods", 
"    type: numeric", "    range: [10, 90]", "", "  - name: longest_cycle", 
"    source: E8. During the last 6 months, what was the longest", 
"    domain: Obstetrics & gynaecology", "    label: Longest bleeding (days)", 
"    type: numeric", "    range: [10, 90]", "", "  - name: shortest_cycle", 
"    source: E9. During the last 6 months, what was the shortest", 
"    domain: Obstetrics & gynaecology", "    label: Shortest bleeding (days)", 
"    type: numeric", "    range: [5, 60]", "", "  - name: imb", 
"    source: E10.In the past 6 months, have you experienced bleeding", 
"    domain: Obstetrics & gynaecology", "    label: Intermenstrual spotting", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "", "  - name: self_vol", 
"    source: E11. During the last 6 months, how would you characterize", 
"    domain: Obstetrics & gynaecology", "    label: Self-reported volume", 
"    type: factor", "    levels: [Light, Normal, Heavy]", "    required: true", 
"", "  - name: gravidity", "    source: E19. How many times have you been pregnant", 
"    domain: Obstetrics & gynaecology", "    label: Number of pregnancies", 
"    type: numeric", "    range: [0, 15]", "", "  - name: ever_pregnant", 
"    source: H10. Have you ever been pregnant", "    domain: Obstetrics & gynaecology", 
"    label: Ever pregnant", "    type: binary", "    levels: [\"No\", \"Yes\"]", 
"", "  - name: pelvic_pain", "    source: I42. If you experience pelvic", 
"    domain: Obstetrics & gynaecology", "    label: Pelvic pain severity (0-10)", 
"    type: numeric", "    range: [0, 10]", "", "  # --- Medical history -----------------------------------------------------", 
"", "  - name: chronic_illness", "    source: C2. Do you currently have any chronic", 
"    domain: Medical history", "    label: Chronic illness", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "    required: true", 
"", "  - name: recent_malaria", "    source: C3. Malaria", "    domain: Medical history", 
"    label: Recent malaria", "    type: binary", "    levels: [\"No\", \"Yes\"]", 
"", "  - name: recent_uti", "    source: C7. Urinary Tract Infection", 
"    domain: Medical history", "    label: Recent UTI", "    type: binary", 
"    levels: [\"No\", \"Yes\"]", "", "  - name: peptic_ulcer", 
"    source: C9. Peptic Ulcer", "    domain: Medical history", 
"    label: Peptic ulcer", "    type: binary", "    levels: [\"No\", \"Yes\"]", 
"", "  - name: iron_supplements", "    source: C15. Have you taken any iron supplements or multi-vitamins", 
"    domain: Medical history", "    label: Iron or multivitamin supplements", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "", "  - name: treated_anaemia", 
"    source: H4. Have you ever been treated for anemia", "    domain: Medical history", 
"    label: Treated for anaemia", "    type: binary", "    levels: [\"No\", \"Yes\"]", 
"", "  - name: family_bleeding", "    source: H5. Has anyone in your family ever been diagnosed with a bleeding", 
"    domain: Medical history", "    label: Family bleeding disorder", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "", "  - name: dental_bleed", 
"    source: H6. Have you ever had a tooth extracted", "    domain: Medical history", 
"    label: Bleeding after dental work", "    type: binary", 
"    levels: [\"No\", \"Yes\"]", "", "  - name: other_surgery", 
"    source: H8. Have you ever had surgery other than dental", 
"    domain: Medical history", "    label: Bleeding after surgery", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "", "  - name: easy_bruising", 
"    source: H12. Do you have a history of easy bruising", "    domain: Medical history", 
"    label: Easy bruising/nosebleeds", "    type: binary", "    levels: [\"No\", \"Yes\"]", 
"", "  - name: sought_care", "    source: I36. Have you sought health care for menstrual", 
"    domain: Medical history", "    label: Sought care for periods", 
"    type: binary", "    levels: [\"No\", \"Yes\"]", "", "  # --- Clinical measurements -----------------------------------------------", 
"", "  - name: bmi", "    source: F6. BMI is", "    domain: Clinical measurements", 
"    label: Body mass index", "    type: numeric", "    range: [12, 60]", 
"    required: true", "", "  - name: weight_kg", "    source: \"Average Weight:\"", 
"    domain: Clinical measurements", "    label: Weight (kg)", 
"    type: numeric", "    range: [25, 150]", "    required: true", 
"", "  - name: height_cm", "    source: \"Average Height:\"", 
"    domain: Clinical measurements", "    label: Height (cm)", 
"    type: numeric", "    range: [120, 200]", "    required: true", 
"", "  - name: sbp", "    source: Average - Systolic BP", "    domain: Clinical measurements", 
"    label: Systolic BP (mmHg)", "    type: numeric", "    range: [70, 220]", 
"    required: true", "", "  - name: dbp", "    source: Average - Diastolic BP", 
"    domain: Clinical measurements", "    label: Diastolic BP (mmHg)", 
"    type: numeric", "    range: [40, 140]", "    required: true", 
"", "  - name: map", "    domain: Clinical measurements", "    label: Mean arterial pressure", 
"    type: derived", "    expr: (sbp + 2 * dbp) / 3", "    range: [40, 160]", 
"", "  - name: heart_rate", "    source: \"Average Heart Rate:\"", 
"    domain: Clinical measurements", "    label: Heart rate (bpm)", 
"    type: numeric", "    range: [40, 160]", "    required: true", 
"", "  - name: temperature", "    # The export header carries a Latin-1 degree sign; match on the ASCII part", 
"    # so the spec itself stays plain ASCII.", "    source: Average Temperature", 
"    domain: Clinical measurements", "    label: Temperature (C)", 
"    type: numeric", "    range: [34, 42]", "", "  # --- Ultrasound ----------------------------------------------------------", 
"", "  - name: endo_thickness", "    source: S13. Endometrial thickness", 
"    domain: Ultrasound", "    label: Endometrial thickness (mm)", 
"    type: numeric", "    range: [0, 40]", "", "  - name: uterus_position", 
"    source: S2. Position of the uterus", "    domain: Ultrasound", 
"    label: Uterine position", "    type: factor", "    levels: [Anteverted, Retroverted, Others]", 
"", "  - name: myo_texture", "    source: S5. What is the myometrial echo texture", 
"    domain: Ultrasound", "    label: Myometrial echo texture", 
"    type: factor", "    levels: [Homogenous, Heterogenous, Others]", 
"", "  - name: endo_pattern", "    source: S15. Endometrial echo pattern", 
"    domain: Ultrasound", "    label: Endometrial echo pattern", 
"    type: factor", "    levels: [Uniform, Bright edge, Non-uniform]", 
"", "  # --- Laboratory ----------------------------------------------------------", 
"", "  - name: haemoglobin", "    source: HGB", "    domain: Laboratory", 
"    label: Haemoglobin (g/dL)", "    type: numeric", "    range: [3, 20]", 
"", "  - name: serum_ferritin", "    source: Serum Ferritin", 
"    domain: Laboratory", "    label: Serum ferritin (ng/mL)", 
"    type: numeric", "    range: [0, 500]", "", "  - name: serum_iron", 
"    source: Serum Iron", "    domain: Laboratory", "    label: Serum iron (ug/dL)", 
"    type: numeric", "    range: [0, 400]", "", "  # --- Mental health & QoL -------------------------------------------------", 
"  #", "  # Item blocks are matched by pattern, but `n_items` is asserted: if the form", 
"  # gains or loses an item the build fails rather than quietly rescaling.", 
"", "  - name: phq9_depression", "    domain: Mental health & QoL", 
"    label: Depression severity (PHQ-9)", "    type: derived", 
"    fn: item_mean", "    args:", "      pattern: \"^L\\\\d+\\\\.\"", 
"      n_items: 9", "      min_answered: 5", "      scores:", 
"        Not at all: 0", "        Several days: 1", "        More than half the days: 2", 
"        Nearly every day: 3", "", "  - name: gad7_anxiety", 
"    domain: Mental health & QoL", "    label: Anxiety severity (GAD-7)", 
"    type: derived", "    fn: item_mean", "    args:", "      pattern: \"^M\\\\d+\\\\.\"", 
"      n_items: 7", "      min_answered: 4", "      scores:", 
"        Not at all: 0", "        Several days: 1", "        More than half the days: 2", 
"        Nearly every day: 3", "", "  - name: pms_score", "    domain: Mental health & QoL", 
"    label: Premenstrual symptom score", "    type: derived", 
"    fn: item_mean", "    args:", "      pattern: \"^J\\\\d+\\\\.\"", 
"      n_items: 8", "      min_answered: 4", "      scores:", 
"        Not at all: 0", "        Mild: 1", "        Moderate: 2", 
"        Severe: 3", "", "  - name: qol_score", "    domain: Mental health & QoL", 
"    label: Menstrual QoL burden", "    type: derived", "    fn: item_mean", 
"    args:", "      pattern: \"^K\\\\d+\\\\.\"", "      n_items: 6", 
"      min_answered: 3", "      scores:", "        Never: 0", 
"        Once or twice: 1", "        A few times: 2", "        In most periods: 3", 
"        In every period: 4", "", "# ---------------------------------------------------------------------------", 
"# Consistency rules. Each `expr` must evaluate to TRUE for a plausible record.", 
"# Rows where the expression is NA are not evaluable and are excluded from the", 
"# denominator rather than counted as passes.", "# ---------------------------------------------------------------------------", 
"", "checks:", "  - name: Age at menarche < current age", "    expr: age_menarche < age", 
"  - name: Longest bleeding >= shortest bleeding", "    expr: longest_cycle >= shortest_cycle", 
"  - name: Active bleeding days <= cycle length", "    expr: bleeding_days <= cycle_length", 
"  - name: Systolic BP >= diastolic BP", "    expr: sbp >= dbp", 
"  - name: BMI within 12-60", "    expr: bmi >= 12 & bmi <= 60", 
"  - name: Heart rate within 40-160", "    expr: heart_rate >= 40 & heart_rate <= 160"
)

# ==== inst/report.Rmd (282 lines) ====
.embedded[["inst/report.Rmd"]] <-
c("---", "title: \"`r params$title_override`\"", "date: \"`r format(Sys.Date(), '%d %B %Y')`\"", 
"output:", "  word_document:", "    toc: true", "    toc_depth: 2", 
"params:", "  data_file: NULL", "  spec_file: NULL", "  r_dir: NULL", 
"  title_override: \"Cohort Profile\"", "---", "", "```{r setup, include = FALSE}", 
"knitr::opts_chunk$set(", "  echo = FALSE, message = FALSE, warning = FALSE,", 
"  fig.width = 6.5, fig.height = 4.2, dpi = 200", ")", "", "# The report renders once per output format, and Fisher's exact test uses", 
"# simulated p-values. Without a fixed seed the DOCX and HTML versions would", 
"# carry slightly different numbers — exactly the disagreement between", 
"# formats this project promises cannot happen.", "set.seed(20260630)", 
"", "# The report is rendered in a fresh environment, so bring the analysis code in", 
"# explicitly rather than relying on anything being attached already.", 
"if (!is.null(params$r_dir)) {", "  for (f in list.files(params$r_dir, pattern = \"\\\\.R$\", full.names = TRUE)) {", 
"    source(f, local = TRUE)", "  }", "}", "", "spec <- read_spec(params$spec_file)", 
"raw  <- read_export(params$data_file)", "", "validation <- validate_export(raw, spec)", 
"stop_if_invalid(validation)", "", "analysis <- build_analysis_data(raw, spec, validation)", 
"quality  <- data_quality(analysis)", "", "y_name <- spec$outcome$name", 
"outcome_tab <- table(analysis[[y_name]])", "n_analytic  <- nrow(analysis)", 
"", "# Only domains that actually have data become sections.", 
"live_domains <- Filter(function(dm) length(domain_vars(analysis, spec, dm)) > 0,", 
"                       spec$domains)", "```", "", "```{r title-block, results = \"asis\"}", 
"cat(\"# Overview\\n\\n\")", "```", "", "This report describes **`r n_analytic` participants** from the", 
"`r spec$study` study and tests each variable one at a time against the", 
"outcome, **`r spec$outcome$label`**.", "", "The upload contained `r validation$n_rows` rows. After keeping only", 
"`r spec$filter$event_value` records with an outcome result,", 
"`r n_analytic` participants remain.", "", "```{r overview-outcome}", 
"ov <- data.frame(", "  Group = names(outcome_tab),", "  N = as.integer(outcome_tab),", 
"  `%` = sprintf(\"%.1f%%\", 100 * as.integer(outcome_tab) / n_analytic),", 
"  check.names = FALSE, stringsAsFactors = FALSE", ")", "style_table(flextable::flextable(ov), title = \"Outcome distribution\")", 
"```", "", "Every association below is **unadjusted**. Multivariable modelling is", 
"deliberately out of scope for this report.", "", "# Data quality", 
"", "```{r dq-intro, results = \"asis\"}", "issues <- c(", "  length(quality$soft),", 
"  if (!is.null(quality$out_of_range)) nrow(quality$out_of_range) else 0,", 
"  if (!is.null(quality$bad_levels)) nrow(quality$bad_levels) else 0,", 
"  if (!is.null(quality$high_missing)) nrow(quality$high_missing) else 0", 
")", "if (sum(issues) == 0) {", "  cat(\"No data-quality problems were found. Every variable in the spec matched\",", 
"      \"a column, all values were inside their declared ranges, and every\",", 
"      \"response was one the spec declares.\\n\\n\")", "} else {", 
"  cat(\"The export passed the checks needed to run the analysis. The points\",", 
"      \"below did not stop the report but are worth knowing about when reading\",", 
"      \"it.\\n\\n\")", "}", "```", "", "```{r dq-soft, results = \"asis\"}", 
"if (length(quality$soft)) {", "  cat(\"## Columns the spec expected but did not find\\n\\n\")", 
"  for (f in quality$soft) cat(\"- \", f$message, \"\\n\", sep = \"\")", 
"  cat(\"\\n\")", "}", "```", "", "```{r dq-range, results = \"asis\"}", 
"ft <- range_flextable(quality)", "if (!is.null(ft)) {", "  cat(\"## Values outside the plausible range\\n\\n\")", 
"  flextable::flextable_to_rmd(ft)", "  cat(\"\\n\")", "}", "```", 
"", "```{r dq-levels, results = \"asis\"}", "ft <- levels_flextable(quality)", 
"if (!is.null(ft)) {", "  cat(\"## Responses the spec does not declare\\n\\n\")", 
"  cat(\"These were left as missing. They are never folded into an existing\",", 
"      \"category, because that would hide a change in how the question is\",", 
"      \"coded.\\n\\n\")", "  flextable::flextable_to_rmd(ft)", 
"  cat(\"\\n\")", "}", "```", "", "```{r dq-highmiss, results = \"asis\"}", 
"hm <- quality$high_missing", "if (!is.null(hm) && nrow(hm)) {", 
"  cat(\"## Variables above the missingness threshold\\n\\n\")", 
"  cat(sprintf(\"More than %.0f%% missing. Summaries for these are based on very few participants.\\n\\n\",", 
"              100 * spec$options$missingness_threshold))", "  for (i in seq_len(nrow(hm))) {", 
"    cat(sprintf(\"- %s: %.1f%% missing\\n\", hm$label[i], hm$pct_missing[i]))", 
"  }", "  cat(\"\\n\")", "}", "```", "", "# Descriptive tables by outcome status", 
"", "```{r descriptives, results = \"asis\"}", "letters_seq <- letters[seq_along(live_domains)]", 
"for (i in seq_along(live_domains)) {", "  dm <- live_domains[[i]]", 
"  ft <- descriptive_flextable(", "    analysis, spec, dm,", 
"    title = sprintf(\"Table 1%s. %s by %s status\", letters_seq[i], dm,", 
"                    outcome_positive_label(spec)))", "  if (is.null(ft)) next", 
"  cat(\"\\n## \", dm, \"\\n\\n\", sep = \"\")", "  flextable::flextable_to_rmd(ft)", 
"  cat(\"\\n\")", "}", "```", "", "# Missingness", "", "## Per-variable missingness", 
"", "```{r missingness}", "missingness_flextable(quality, spec)", 
"```", "", "## Missingness mechanism", "", "```{r mcar, results = \"asis\"}", 
"mc <- mcar_result(analysis, spec)", "if (isTRUE(mc$ok)) {", 
"  cat(sprintf(", "    paste(\"Little's test for data missing completely at random was run over the\",", 
"          \"%d numeric variables below the %.0f%% missingness threshold.\",", 
"          \"The statistic is %.1f on %d degrees of freedom (p = %s), across %d\",", 
"          \"missingness patterns.\\n\\n\"),", "    mc$n_vars, 100 * spec$options$missingness_threshold,", 
"    mc$statistic, mc$df, fmt_p(mc$p.value), mc$missing.patterns))", 
"  if (length(mc$dropped)) {", "    cat(sprintf(paste(\"%s %s left out of this test because %s an exact\",", 
"                      \"combination of other variables.\\n\\n\"),", 
"                paste(mc$dropped, collapse = \", \"),", "                if (length(mc$dropped) == 1) \"was\" else \"were\",", 
"                if (length(mc$dropped) == 1) \"it is\" else \"they are\"))", 
"  }", "  cat(if (!is.na(mc$p.value) && mc$p.value < 0.05) {", 
"    paste(\"A small p-value argues against missing completely at random, so\",", 
"          \"a complete-case analysis may be biased.\\n\\n\")", 
"  } else {", "    paste(\"There is no strong evidence against missing completely at random\",", 
"          \"among these variables.\\n\\n\")", "  })", "} else {", 
"  cat(mc$message, \"\\n\\n\")", "}", "```", "", "```{r missing-vs-outcome}", 
"mv <- missing_vs_outcome(analysis, spec)", "missing_vs_outcome_flextable(mv)", 
"```", "", "# Variable consistency checks", "", "```{r checks, results = \"asis\"}", 
"ft <- checks_flextable(quality)", "if (is.null(ft)) {", "  cat(\"The spec declares no consistency rules.\\n\\n\")", 
"} else {", "  cat(\"Each rule below should hold for a plausible record. Records where the\",", 
"      \"rule cannot be evaluated, usually because one of the variables is\",", 
"      \"missing, are excluded from the denominator rather than counted as\",", 
"      \"passing.\\n\\n\")", "  flextable::flextable_to_rmd(ft)", 
"  cat(\"\\n\")", "}", "```", "", "# Plots of key variables versus the outcome", 
"", "```{r plots, fig.height = 5.2}", "uni_all <- univariate_results(analysis, spec, live_domains)", 
"p <- outcome_plots(analysis, spec, uni_all)", "if (!is.null(p)) p", 
"```", "", "```{r plots-note, results = \"asis\"}", "if (is.null(p)) cat(\"No numeric variables were estimable, so there is nothing to plot.\\n\\n\")", 
"```", "", "# Univariate logistic associations", "", "Each variable is entered on its own. Odds ratios are unadjusted, with Wald", 
"95% confidence intervals. A variable is reported as **not estimable** rather", 
"than given a number when it has fewer than", "`r spec$options$min_complete_cases` complete cases, has no variation, or", 
"separates the outcome perfectly — a separating variable would otherwise", 
"produce an enormous odds ratio that reads as a finding.", "", 
"```{r univariate, results = \"asis\"}", "for (dm in live_domains) {", 
"  res <- univariate_results(analysis, spec, dm)", "  ft <- univariate_flextable(", 
"    res, title = sprintf(\"Univariate associations: %s\", dm))", 
"  if (is.null(ft)) next", "  cat(\"\\n## \", dm, \"\\n\\n\", sep = \"\")", 
"  flextable::flextable_to_rmd(ft)", "  cat(\"\\n\")", "}", "```", 
"", "```{r nonestimable, results = \"asis\"}", "ne <- uni_all[nzchar(uni_all$note), , drop = FALSE]", 
"if (!is.null(ne) && nrow(ne)) {", "  cat(\"## Variables reported as not estimable\\n\\n\")", 
"  for (i in seq_len(nrow(ne))) {", "    cat(sprintf(\"- **%s** — %s\\n\", ne$label[i], ne$note[i]))", 
"  }", "  cat(\"\\n\")", "}", "```", "", "# Notes and caveats", 
"", "- Every association in this report is **unadjusted**. No variable is", 
"  controlled for any other. Multivariable and penalised models are out of", 
"  scope here and live in a separate pipeline.", "- Continuous variables are summarised as median [IQR] and mean (SD) and", 
"  compared with the Wilcoxon rank-sum test, which does not assume normality.", 
"- Categorical variables are compared with Pearson's chi-square, falling back", 
"  to a simulated Fisher's exact test when any expected cell count is below", 
"  five.", "- Values outside the ranges declared in the spec were set to missing before", 
"  analysis. The count of such values is in the data-quality section.", 
"- Responses not declared in the spec were treated as missing rather than", 
"  grouped into an existing category.", "- p-values are not adjusted for multiple comparisons. With this many tests,", 
"  some results at p < 0.05 are expected by chance alone.", "", 
"```{r provenance, results = \"asis\"}", "cat(sprintf(\"\\n---\\n\\nSource file: `%s`  \\nSpec: `%s`  \\nGenerated: %s\\n\",", 
"            basename(params$data_file), basename(params$spec_file),", 
"            format(Sys.time(), \"%Y-%m-%d %H:%M\")))", "```"
)

# --- materialize the embedded files and run ---------------------------------

code_dir <- file.path(tempdir(), "cohort-profiler-embedded")
unlink(code_dir, recursive = TRUE)
for (path in names(.embedded)) {
  full <- file.path(code_dir, path)
  dir.create(dirname(full), recursive = TRUE, showWarnings = FALSE)
  writeLines(.embedded[[path]], full, useBytes = FALSE)
}
for (f in list.files(file.path(code_dir, "R"), pattern = "\\.R$",
                     full.names = TRUE)) {
  source(f)
}
options(cohortprofiler.home = code_dir)
spec_file <- file.path(code_dir, "spec", "vital-hmb.yaml")
message("Analysis code: OK (embedded)")

pdf_ok <- soffice_available()
message(if (pdf_ok) "LibreOffice: OK -- you will get DOCX, HTML and PDF"
        else paste("LibreOffice: not found -- you will get DOCX and HTML.",
                   "For a PDF too, install it free from https://libreoffice.org",
                   "and run this again (or open the Word file and Save As PDF)."))

args <- commandArgs(trailingOnly = TRUE)
data_file <- if (length(args) >= 1) args[[1]] else if (interactive()) {
  message("Choose your REDCap export (.csv) in the file dialog ...")
  file.choose()
} else {
  stop("Usage: Rscript run_report_standalone.R export.csv [output_dir]",
       call. = FALSE)
}
if (!file.exists(data_file)) {
  stop('Data file not found: "', data_file, '"', call. = FALSE)
}

out_dir <- if (length(args) >= 2) args[[2]] else {
  file.path(dirname(normalizePath(data_file)),
            paste0("cohort-report-", format(Sys.Date(), "%Y-%m-%d")))
}

message("\nBuilding the report from: ", basename(data_file))
message("This takes about half a minute ...\n")

result <- tryCatch(
  render_report(
    data_file = data_file,
    spec_file = spec_file,
    out_dir = out_dir,
    basename_out = paste0(tools::file_path_sans_ext(basename(data_file)),
                          "-report"),
    formats = if (pdf_ok) c("docx", "pdf", "html") else c("docx", "html")
  ),
  error = function(e) e
)

if (inherits(result, "error")) {
  message("\n", conditionMessage(result))
  quit(save = "no", status = 1)
}

message("Done. Your report:")
for (p in result) message("  ", normalizePath(p))
if (interactive()) utils::browseURL(out_dir)

